### ISSUE TITLE
'MatrixFactorizationTrainer.Options' does not contain a definition for 'K'

### ISSUE THREAD

**Issue by khteh** [dotnet/machinelearning-samples#1023]
https://github.com/dotnet/machinelearning-samples/tree/main/samples/csharp/getting-started/MatrixFactorization_ProductRecommendation

Where is the `K` param?

**Comment by feiyun0112** [comment]
it rename to `ApproximationRank `

https://github.com/dotnet/machinelearning/blob/72cfdf611a510ba0570170a708ddcc1a1928f329/src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs#L193
