### ISSUE TITLE
In GitHubLabeler project, TextLoader should be made `useHeader` is true

### ISSUE THREAD

**Issue by zhengchun** [dotnet/machinelearning-samples#11]
https://github.com/dotnet/machinelearning-samples/blob/2bf33da58b8b205b4a3b9e004da4a8f761d02477/samples/end-to-end-apps/github-labeler/GitHubLabeler/Predictor.cs#L25

should be:

```c#
pipeline.Add(new TextLoader(DataPath).CreateFrom<GitHubIssue>(useHeader: true));
````

if `useHeader=false` that means in  `corefx-issues-train.tsv` data file , a first row `Area` label will be as a new category and total number of category is `23`, not `22`.

**Comment by OliaG** [comment]
Thanks @zhengchun for reporting the issue and @jwood803  for the fix!
