### ISSUE TITLE
F# samples need to be migrated to ML.NET v0.7 (minor migration from v0.6)

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning-samples#117]
We released v0.7 today (Nov. 6th) and there are a few minor breaking changes compared to v0.6 in some Estimators naming, most of all.
For now, I'm setting a special "Directory.Build.props" file targeting v0.6 for the F# samples until they are migrated to v0.7.

C# samples are most of them already migrated to v0.7, so contributors for F# can check it out in regards naming, etc.

**Comment by kunjee17** [comment]
@mariuszwojcik let's go for it. Which one you are picking up? 

@CESARDELATORRE is it ok if we use paket instead of nuget for F# samples ? F# community like that way. If you want  I can open up new issue to discuss this.

**Comment by CESARDELATORRE** [comment]
Sure, open an issue and let's discuss it with @dsyme ok? 👍

**Comment by mariuszwojcik** [comment]
@kunjee17 hey, welcome back, hope you had great holiday. The basic four samples are already on v0.7. I am working on porting "Fraud detection" to F#, so if you wish you could port any other sample.

**Comment by kunjee17** [comment]
@mariuszwojcik is your samples are already merged ? I ll pick it others. And also mention them here so we can stay in sync.

**Comment by mariuszwojcik** [comment]
@kunjee17 when you get the latest, all F# samples are in v0.7 and as I said, I am working on *Fraud Detection*

**Comment by CESARDELATORRE** [comment]
@mariuszwojcik @kunjee Hey guys! Thanks a lot for your work migrating the F# samples. We really appreciate it from Microsoft! 👍  - About continuing with further samples for F#, just a heads-up. 
Honoring your time, It'd be better if you still don't migrate ALL the C# samples, as some of them still will be refactored quite a lot. Especially the ones who are still not using the "common code".

I'd suggest if you want to migrate the following three samples, only, for now:
- Regression_BikeSharingDemand
- MulticlassClassification-GitHubLabeler
- Clustering_CustomerSegmentation

And even those (and the rest) might slightly be refactored in the upcoming days while reviewing the samples from an API point of view.

But do NOT migrate the following as they will evolve quite a lot until we align them to the rest of samples:
- eShopDashboardML
- BinaryClassification_CreditCardFraudDetection
- DeepLearning_ImageClassification_TensorFlow	
- DeepLearning_TensorFlowEstimator

Thanks! 👍

**Comment by mariuszwojcik** [comment]
@CESARDELATORRE thanks for the heads up - much appreciated. In that case I will focus my efforts on *Regression_BikeSharingDemand* for now.

Cheers!

**Comment by mariuszwojcik** [comment]
*Regression_BikeSharingDemand* sample has been migrated to F#. Next one to go would be *MulticlassClassification-GitHubLabeler*

Cheers

**Comment by kunjee17** [comment]
I ll try for Clustering_CustomerSegmentation.

**Comment by mariuszwojcik** [comment]
@kunjee17 there already is a common folder which is reused between all samples. You'll find there `ModelBuilder` and `ModelScorer` modules as well as `ConsoleHelper`. This follows C# samples and I think keeping them *in similar structure* will be beneficial for people learning how to use **ML.NET** as they will be able to easily follow C# and F# samples.
I was thinking to move several samples to F#, see what code requires *fsharp-isation* and then move it to dedicated assembly which can be reused. The first attempt was a `Pipeline` module, but since then the logic moved to the `ModelBuilder`. Currently, the project changes a lot so it may be bit too early for this, but definitely we should think about it. Cheers

**Comment by mariuszwojcik** [comment]
@CESARDELATORRE, earlier you mentioned that below projects will be going through major code changes and we should not convert them to F# yet. Can you update us on the status? I have just migrated `MulticlassClassification-GitHubLabeler` sample and am looking for next task :)

* eShopDashboardML
* BinaryClassification_CreditCardFraudDetection
* DeepLearning_ImageClassification_TensorFlow
* DeepLearning_TensorFlowEstimator

**Comment by CESARDELATORRE** [comment]
I would wait some more time until the API is even more stable. Updating all the samples to F# every month means a significant amount of work.
I'm closing this issue. If needed let's create new issues for particular F# topics.

**Comment by CESARDELATORRE** [comment]
Closing this issue as it is stale
