### ISSUE TITLE
Move at least F# samples to Paket

### ISSUE THREAD

**Issue by kunjee17** [dotnet/machinelearning-samples#122]
[Paket](https://github.com/fsprojects/Paket) is default package manager for almost every F# project. If you skip few Xamarin once. 

Instead of going into discussion that which one is better, I just like to propose paket for at least F# samples purely based on popularity within community. 

If C# samples or ML.Net like to add paket support I am very much happy to help in that. But for now, for this repo it would be great if at least F# samples moved to paket. 

cc/ @dsyme @CESARDELATORRE @mariuszwojcik

**Comment by CESARDELATORRE** [comment]
@kunjee17 - Are the preview/daily-builds of ML.NET like 0.8.xxx-Preview we have in MyGet available through Paket? - That can be an issue when we're migrating to newer versions that are still not officially released at NuGet or Paket..

**Comment by kunjee17** [comment]
@CESARDELATORRE are talking about this support or something else ? https://docs.myget.org/docs/how-to/using-paket-with-myget-feeds

**Comment by CESARDELATORRE** [comment]
Right. Looks like there's no issue and from Paket we can also use the preview/daily-builds of ML.NET like now 0.8.xxx-Preview which we might need when migrating, eventually. Then I'm okay.
My point is that for ML.NET we use the following feeds:

Official releases at NuGet:
https://api.nuget.org/v3/index.json 

MyGet feed (Try this for any ML.NET 0.8.xxx-Preview version):
https://dotnet.myget.org/F/dotnet-core/api/v3/index.json 

Sinec Paket is the by default choice for F#, I see no issues from my part about using Paket for all F# samples. 

But I also would like to have the confirmation from:
 @dsyme, @asthana86

**Comment by prathyusha12345** [comment]
Closing this issue. For now we want a single source of truth in NuGet for the packages.
Now, heading v1.0, If you feel strong about wanting Paket for ML.NET packages, please open an issue at the ML.NET repo, here:  

https://github.com/dotnet/machinelearning/issues
