### ISSUE TITLE
Namesapces in Samples do not exist

### ISSUE THREAD

**Issue by dbaechtel** [dotnet/machinelearning-samples#125]
The following Namespaces for the C# samples do not exist.
Where can I find them?

using Microsoft.ML.Core.Data;
using Microsoft.ML.Transforms.Categorical;
using static Microsoft.ML.Transforms.Normalizers.NormalizingEstimator;

**Comment by CESARDELATORRE** [comment]
Not sure what you mean with "namespaces do not exist". All the samples compile and run properly.
The namespaces are coming from the ML.NET NuGet package here: 
https://www.nuget.org/packages/Microsoft.ML/

The NuGet feed you can use/check in VS is: 
`https://api.nuget.org/v3/index.json`
(Which is the regular NuGet feed).

In what example are you having that issue?

If you need a "Getting Started" for ML.NET, follow this:
https://www.microsoft.com/net/learn/machinelearning-ai/ml-dotnet-get-started-tutorial

Or any of the Tutorials here:
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/

**Comment by CESARDELATORRE** [comment]
Closing this issue. Re-open if needed.
