### ISSUE TITLE
Bounding boxes while classifying images with ML.NET?

### ISSUE THREAD

**Issue by oakmangit** [dotnet/machinelearning-samples#127]
Hi there,

Does ML.NET support extracting bounding boxes for predictions when classifying images?

**Comment by CESARDELATORRE** [comment]
When classifying images you need to use any trained model either TensorFlow or ONNX model.
With ML.NET you are just scoring/running the trained model.
Therefore, in regards bounding boxes or any other feature, it'll depend on what the TensorFlow or ONNX model supports, not really about ML.NET.
Closing the issue.
