### ISSUE TITLE
LocalEnvironment could load it due to low access level

### ISSUE THREAD

**Issue by DevLob-zz** [dotnet/machinelearning-samples#130]
LocalEnvironment could load it due to low access level 

any help please

**Comment by CESARDELATORRE** [comment]
Can you provide further info?
Note that since v0.7 you shouldn't use LocalEnvironment but MLContext.
Still, I'm not sure what your issue is about, can you provide further context and if this is an error/exception provide the full error stack?
Thanks,

**Comment by CESARDELATORRE** [comment]
Closing this issue as it is stale.
