### ISSUE TITLE
How to use Feature selection

### ISSUE THREAD

**Issue by Vijay27anand** [dotnet/machinelearning-samples#136]
I want to use FeatureSelectorByMutualInformation feature selection, can you please provide me a sample code snippet how to use it with a dataset, i could not able find in the samples provided.

**Comment by asthana86** [comment]
@Zruty0  is out on parental leave. Tom/Ivan can you folks help answer Vijay's query. 
@Ivanidzo4ka @TomFinley

**Comment by Ivanidzo4ka** [comment]
Sure.
https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/FeatureSelectionTransform.cs
Here is example of our Count selection and Mutual information transforms in action.
They are gonna be part of 0.8 release (which is around the corner) but you can always try our daily nugets to test them.

**Comment by Vijay27anand** [comment]
Thanks @Ivanidzo4ka it was helpful. I need more details on how to get the scores of individual columns similar to what we get from Azure ML Studio. I have attached the sample ML studio screen shot that showing the score of columns. Similar to this i want to identify the top columns to consider for my Label.
![azureml-mi](https://user-images.githubusercontent.com/8811335/49211620-fcd9e980-f3e5-11e8-92c9-3ce439bbe145.jpg)

**Comment by CESARDELATORRE** [comment]
@Vijay27anand - As Ivan mentioned, with the upcoming ML.NET v08 version we're also releasing improved model explainability, so in 0.8 release, we have included tools for model explainability that we use internally at Microsoft to help machine learning developers better understand the feature importance of models ("Permutation Feature Importance") and create high-capacity models that can be easily interpreted by others ("Generalized Additive Models").
I'm writing a blog post including these features which will be published next week. Stay tuned and check it out next week at the .NET Blog, on? 👍

**Comment by Vijay27anand** [comment]
@CESARDELATORRE  with 0.8 the MutualInformationFeatureSelectionUtils.Train seems to be removed, i was using to understand the score for the columns in the Mutual feature selection. Please let me know which on should i use now.

**Comment by CESARDELATORRE** [comment]
Adding @rogancarr - Rogan, is there something comparable to MutualInformationFeatureSelectionUtils.Train in the new model features explainability coming in 0.8?
Any other choice to understand the score for the columns in the **Mutual feature selection**?

**Comment by Vijay27anand** [comment]
@CESARDELATORRE @rogancarr can you answer how to understand the score for the columns in the **Mutual feature selection** in 0.8

**Comment by Vijay27anand** [comment]
it will be implemented with #2328

**Comment by justinormont** [comment]
https://github.com/dotnet/machinelearning/issues/2328
