### ISSUE TITLE
StochasticDualCoordinateAscentClassifier Issue With 86 bit 

### ISSUE THREAD

**Issue by DevLob-zz** [dotnet/machinelearning-samples#139]
when i use StochasticDualCoordinateAscentClassifier Issue With 86 bit 

it through the following exception
'A call to PInvoke function 'Microsoft.ML.CpuMath!Microsoft.ML.Runtime.Internal.CpuMath.Thunk::SumSqU' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

but when used it with 64 it work 

unfortunately i need to integrate it with 32 bit application

any advice pleas e

this sample of my code

             `   pipeline.Add(CollectionDataSource.Create(noramalTagsTrainingData));

                pipeline.Add(new Dictionarizer("Label"));
                // Transform any text feature to numeric values
                pipeline.Add(new CategoricalOneHotVectorizer(
                   "fontColor",
                   "tagText",
                   "firstWord"
                   ));
              
pipeline.Add(new ColumnConcatenator(
                    "Features",
                    "fontSize",
                    "isBold",
                    "isItalic",
                    "isUnderLine",
                    "containsDot",
                    "containsQuestionMark",
                    "isAllCaps",
                    "tagText",
                    "firstWord"
                    ));

                pipeline.Add(new StochasticDualCoordinateAscentClassifier
                {
                    MaxIterations = 100,
                    NumThreads = 7,
                    LossFunction = new SmoothedHingeLossSDCAClassificationLossFunction()
                });
pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedLabel" });

                // The pipeline is trained on the dataset that has been loaded and transformed.
                var model = pipeline.Train<NormalTagsModelFeatures, NormalTagsPrediction>();`
it through the exception at last line

**Comment by CESARDELATORRE** [comment]
Can you submit this issue at the ML.NET repo?
Looks like it is an issue with the ML.NET libraries when running on 32 bits (x86), not really with the ML.NET samples code themselves, right?

I'm closing this issue here at ML.NET Samples, since looks like it is not really related to the samples.
