### ISSUE TITLE
Sample Requirement for Field Aware Factorization Machines

### ISSUE THREAD

**Issue by Edward-Zhou** [dotnet/machinelearning-samples#142]
For [Movie Recommender](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Recommendation-MovieRecommender), it describe that using `Field Aware Factorization Machines` to add more features like UserId, ProductId, Ratings, Product Description, Product Price etc, but for the demo project, is just analyse the useid and movieid.      

Is there any complete demo to take more features in Recommendation demo?

**Comment by asthana86** [comment]
Thanks for trying out the Movie Recommender. I will add something today and update the sample. Just out of curiosity Edward can you share the recommendation scenario you have. While Movie Recommender is a good fun sample, our belief is that it's not an actual use-case for most folks :).

**Comment by Edward-Zhou** [comment]
Thanks for your reply. For production scenario, I think most would like **Product Recommend** by according the purchase History with features like product category, price, evaluation and etc. And when users shop online, we could recommend which product for shopping and they could buy as need.

**Comment by mirsaeedi** [comment]
Thanks @asthana86 and @Edward-Zhou 
Unfortunately, this sample does not show all capabilities of Field Aware Factorization Machines. I think a good sample is to take User Features and Movie Features into account for training the model. Right now, the sample uses user-movie-rating matrix which is what Matrix Factorization does already.

Is there any sample that shows how to take all the benefits from Field Aware Factorization Machines technique?

**Comment by 1amirjalai** [comment]
> Thanks for trying out the Movie Recommender. I will add something today and update the sample. Just out of curiosity Edward can you share the recommendation scenario you have. While Movie Recommender is a good fun sample, our belief is that it's not an actual use-case for most folks :).

i can't find where you added additional features and could you also please explain why FeaturizeText is used here?

**Comment by prathyusha12345** [comment]
Closing this issue as its stale. Please reopen the issue if you still need assistance. Thanks 👍

**Comment by unruledboy** [comment]
agree with @1amirjalai , @mirsaeedi  , I also could not find the additional features being supported, @Edward-Zhou mentioned here https://github.com/dotnet/machinelearning-samples/issues/43  as well.
