### ISSUE TITLE
F# samples with build errors

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning-samples#167]
@mariuszwojcik - When possible for you, can you take a look to the F# samples? I'm getting build errors in most of the F# samples, since this week.
Thanks,

**Comment by mariuszwojcik** [comment]
@CESARDELATORRE - the problem that `$(MicrosoftMLVersion)` has been updated to v0.8 and there are breaking changes between v0.7 and v0.8. I have referenced v0.7 in F# samples until I update samples to v0.8

**Comment by mariuszwojcik** [comment]
@CESARDELATORRE I think this issue can be closed now.

**Comment by CESARDELATORRE** [comment]
Sure! Closing it! 👍
