### ISSUE TITLE
How to get a predicted group list output?

### ISSUE THREAD

**Issue by therollingbird** [dotnet/machinelearning-samples#175]
is there a way to output grouped items using the prediction algorithm and clustering?
here is an example i have a list of 50 employees and i want  to put them into groups of 10 by predicting which employees best suited to work together in a group and then output those 5 groups with 10 employees each.

the elements that will be used to make the prediction will be (
- experience from 1 - 10 years experience, 
-  easy to work with rated by yes or no options 
- Visual learner vs non visual learner
- and if the employee is a quick learner or not 

thank you in advance :)

 ,

**Comment by asthana86** [comment]
@glebuk @Zruty0 can you help answer this query.

**Comment by glebuk** [comment]
@therollingbird,
The high-level approach to your problem can be solved via clustering as you mentioned.  Please take a look at the iris clustering example  [here](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/iris-clustering).
Basically, you first train a k-means clusterer with k=(number of groups you expect to end up) which is 5 in your example..  Then, get the classId for each employee.  Once each employee has one or more cluster ids assigned to them, just return them as a list, sorted by cluster.
Now, be aware, that this solution will give you groups of most similar people bucketized together. In if you are trying to optimize teams productivity, you might want to try do the exact opposite to ensure that there is a diversity of skills and proper creative tension.

**Comment by therollingbird** [comment]
How would I do diversity with clustering ? That's one of the things I was trying to figure out. Either getting the groups and  doing a manual input Oroing an inverse of the cluster algorithm if it's there

**Comment by therollingbird** [comment]
@glebuk another way I'm thinking is using the knapsack algorithm I'm not sure if ML.net has it, if it does I think that would be the best solution. 

If so my next question is does ML have the knapsack algorithm?

**Comment by glebuk** [comment]
What are you trying to optimize for each group?  If similarity, then clustering is the correct approach.  Knapsack is not really machine learning problem.  It is not surprising that ML.NET does not have it.  It is an NP-complete optimization problem.  There are a few pseudo polynomial approximations using dynamic programming implementations can be found online.

**Comment by glebuk** [comment]
Let me know if there are any further questions.  Feel free to close the issue if it was answered.

**Comment by glebuk** [comment]
In general, training done over streaming data.  We don't want to scan the entire data to count examples before training.  I suggest you implement that logic in your code, by counting the number of training examples and then computing proper K.  also note that we do not know apriori how many items will be in each cluster.  As a result, that number is not known until training is done.

**Comment by prathyusha12345** [comment]
Closing the issue/question as it is stale now.
