### ISSUE TITLE
creditcard.csv data loading error in VB.NET sample

### ISSUE THREAD

**Issue by rrvenki** [dotnet/machinelearning-samples#183]
In CreditCardFraudDetection.Trainer project (VB.NET version), under input folder the creditcard.csv file is generated using the unzip feature in code.  Works fine.
In ConsoleHelpers.vb file, line 100 we get an error "Parsing failed with an exception: Stream reading encountered exception". Detailed Inner Exception as below.

Could not open file 'D:\Source\Repos\machinelearning-samples\samples\visualbasic\getting-started\BinaryClassification_CreditCardFraudDetection\CreditCardFraudDetection.Trainer\bin\Debug\netcoreapp2.1\..\..\..\assets'. Error is: Access to the path 'D:\Source\Repos\machinelearning-samples\samples\visualbasic\getting-started\BinaryClassification_CreditCardFraudDetection\CreditCardFraudDetection.Trainer\assets' is denied.

I'm not a local admin in this PC. creditcard.csv is created from the given zip file by the program running in my user id. I gave full control for the entire root folder. But still no use.  How to get rid of "System.UnauthorizedAccessException"? I understand this is an OS issue not a program issue.  But the program has created this file and the program itself is unable to read it. Please help.

**Comment by CESARDELATORRE** [comment]
We currently have no VB.NET samples in this repo. Only F# and C#. 
Can you specify the source of your VB.NET version of sample? 
Thanks.

**Comment by rrvenki** [comment]
Hi, the source is https://github.com/Nukepayload2/machinelearning-samples/tree/master/samples/visualbasic 


This repo does not have option to raise issues.




Thanks


Raja Venkatesh




Get Outlook for Android







On Mon, Dec 17, 2018 at 10:24 PM +0530, "Cesar De la Torre" <notifications@github.com> wrote:












We currently have no VB.NET samples in this repo. Only F# and C#.

Can you specify the source of your VB.NET version of sample?

Thanks.

**Comment by rrvenki** [comment]
Found bug and resolved the issue.
For project BinaryClassification_CreditCardFraudDetection\CreditCardFraudDetection.Trainer\ModelBuilder.vb file line number 37 is
_dataSetFile = assetsPath
Change this line to
_dataSetFile = Path.Combine(_assetsPath, "input\creditcard.csv")

This will solve the AuthorizationException error.

If this problem is pointing to incorrect repository (C# version), please transfer to VB version as we could not find a way to raise a issue there.

**Comment by justinormont** [comment]
@Nukepayload2: Would it be possible to enable Issues in your repo? Btw, nice to see a VB.NET example.

@CESARDELATORRE: Are we looking to have samples in VB.NET?

**Comment by Nukepayload2** [comment]
@justinormont @CESARDELATORRE I've enabled ISSUES in my VB.NET samples repo.

**Comment by justinormont** [comment]
@Nukepayload2: Thanks much.

**Comment by rrvenki** [comment]
Thank you so much @Nukepayload2 @justinormont and @CESARDELATORRE.




Please bring this item into the issue too.




I believe we should bring as much C# samples to B# soon as it appears F# is next to C# now and B# will loose is lustre. We've to be sharp --> B# !




Get Outlook for Android







On Wed, Dec 19, 2018 at 11:09 PM +0530, "Justin Ormont" <notifications@github.com> wrote:












@Nukepayload2: Thanks much.

**Comment by CESARDELATORRE** [comment]
@rrvenki Please, add your issue and/or fix here at the VB.NET repo:
https://github.com/Nukepayload2/machinelearning-samples/issues

Closing this issue. Thanks! 👍
