### ISSUE TITLE
How to get confidence of prediction for Multi Class Classification for GitHubLabeler

### ISSUE THREAD

**Issue by mikaelm12** [dotnet/machinelearning-samples#185]
I was wondering how to get the confidence level of the predicted label for the Multi Class Classification GitHubLabeler. Or if there was also a way to see the 2nd/3rd options for labels suggested by the model. 
Thanks!

**Comment by asthana86** [comment]
You could use the Score, Probability fields to determine the confidence. You will need to add these fields 
to your output prediction class, here is an example:

e.g. https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/DataStructures/SentimentPrediction.cs#L10

@glebuk can share a snippet on how to see the 2nd/3rd options for labels suggested by the model.

**Comment by mikaelm12** [comment]
That would be very helpful. Thank you!

**Comment by mikaelm12** [comment]
Figured out a solution a few days ago and just thought I'd come back here with it to help anyone else who might want the same thing. 

In the prediction class you have to define an float array for the Score field of the prediction class e.g.
```csharp
public float[] Score { get; set; }
```
 For Multiclass Classification there is no probability field. There's just Score which contains an array of probabilities that the model believes that the current items belongs to each of the classes seen in the training data. 
> Score: Its an array whose length is equal to number of classes and contains probability for each class.

It seems like the order of the probabilities corresponds to the order in which the learner encountered each label in the training data. So with that you can figure out which index corresponds to which label.

I think it might be valuable to add it to the sample for clarity. 

Anyways, thanks for the help 👍

**Comment by asthana86** [comment]
Awesome. Closing this issue.
