### ISSUE TITLE
Probablility in BinaryClassification_CreditCardFraudDetection

### ISSUE THREAD

**Issue by mattdunndc** [dotnet/machinelearning-samples#187]
Below is the output after training the model.  How do you get a Probability/Score of 
Probability: 4.303323E-05  (-25.13374) for a False (Not Fraud)??  Should the probability be a number below 0, like 0.9937543??

Test 5 transactions, from the test datasource, that should be predicted as fraud (true):
----------------------------------------------------------------------------------------
--- Transaction ---
Label: True
Features: [V1] 0.008430365 [V2] 4.137837 [V3] -6.240696 ... [V28] 0.5135738 Amount: 1
Predicted Label: True
Probability: 0.9937543  (12.674)

Test 5 transactions, from the test datasource, that should NOT be predicted as fraud (false):
---------------------------------------------------------------------------------------------
--- Transaction ---
Label: False
Features: [V1] -0.4259659 [V2] 0.9605231 [V3] 1.141109 ... [V28] 0.08108026 Amount: 3.67
Predicted Label: False
**Probability: 4.303323E-05  (-25.13374)**

**Comment by CESARDELATORRE** [comment]
Adding @taranais

**Comment by CESARDELATORRE** [comment]
Closing this issue. I think the probability is right, as I discussed with @taranais.
Thanks,
