### ISSUE TITLE
Remove "Runtime" namespace from example code

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-samples#188]
In https://github.com/dotnet/machinelearning/pull/1956, we removed `Runtime` from the namespaces. 

Now we have to update the example code.

For example, we moved:
* `Microsoft.ML.Runtime.Data` to `Microsoft.ML.Data`
* `Microsoft.ML.Runtime.TimeSeriesProcessing` to `using Microsoft.ML.TimeSeriesProcessing`
* `Microsoft.ML.Runtime.Learners` to `Microsoft.ML.Learners`

I currently see [81 hits](https://github.com/dotnet/machinelearning-samples/search?q=%22ML.Runtime%22&unscoped_q=%22ML.Runtime%22) to `ML.Runtime` in the machinelearning-samples repo.

cc: @JRAlexander, @codemzs

**Comment by prathyusha12345** [comment]
This was fixed already. Closing it.
