### ISSUE TITLE
SentimentAnalysisconsoleApp C# always returns toxic

### ISSUE THREAD

**Issue by JeffCordes** [dotnet/machinelearning-samples#190]
If you run the sentiment analysis project, the TestSinglePrediction method always outputs toxic as a result even if the sample statement is positive.

IE, change the text on line 99 to any good text like:
SentimentIssue sampleStatement = new SentimentIssue { Text = "This is a very great movie" };

and it will still output the result as toxic.

This is in the version 0.8 samples.

**Comment by asthana86** [comment]
We will look into this Jeff, thanks for reporting this issue. @CESARDELATORRE. 

One possibility here could be is that the size of the dataset for Sentiment Analysis we are using is fairly small and could potentially have a bias on more toxic comments. We will update the existing sample with not only the prediction "toxic" or not but also add a probability/score field to help determine how toxic is this comment versus other comments. 

Will this help address your issue?

**Comment by JeffCordes** [comment]
I think thats fair, and inspecting the data set you are correct in that it is rather small and some of the non-toxic examples are still somewhat toxic or passive aggressive.  I think the probability score would help.

Additionally I can try take another open source sentiment dataset like IMDB movie review and see if I can train sentiment analysis with it on ML.net.  Maybe that will be a better test of what I am trying to accomplish.  Though I am on a project and it may be a short delay until i get back to this.

Thanks.

**Comment by justinormont** [comment]
Since this issue has come up various times now, perhaps we should increase the sample size of our dataset. Currently it's using a trivially small sample of the full dataset.

We can increase the size used in our unit tests and examples to a reasonable sample size (or the full for examples).

See: https://github.com/dotnet/machinelearning/issues/708

**Comment by JeffCordes** [comment]
I feel like that is fair.  For reference I had done sentiment analysis samples from Georgia tech, cntk, tensorflow, etc.  Most of them started by downloading a large dataset.  I did "assume" the downloaded dataset would be more thorough.  I feel like it is fair to host large datasets in blob storage and have the git repo samples download them on first run.  Most other frameworks do.
________________________________

**Comment by CESARDELATORRE** [comment]
The wikipedia-detox-250-line-data.tsv dataset is a 250 row sample of the original 160k rows. Training on this small of a sample won't create a useful model.

Let's upload and use the full dataset.
http://aka.ms/tlc-resources/benchmarks/WikiDetoxAnnotated160kRows.tsv

We'll update the status of this issue when the change is made.

**Comment by arafattehsin** [comment]
Dears! I have incorporated the larger data set but the results are nearly same.

**Comment by CESARDELATORRE** [comment]
We updated the sample and now uses a larger dataset and it does not return the same.
Note that it is about "Toxic vs. Not Toxic" content more than "Sentiment Positive vs. Negative".

It is tested and works well.
We've also tested with other datasets like YELP.

**Comment by arafattehsin** [comment]
Awesome!

**Comment by prathyusha12345** [comment]
Closing the issue as its stale and answered. Please reopen if you need any assistance, ok? Thanks :)
