### ISSUE TITLE
How can I recommend products to a new comer in the product recommendation sample?

### ISSUE THREAD

**Issue by DamonJung** [dotnet/machinelearning-samples#192]
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MatrixFactorization_ProductRecommendation

I've heard that one class matrix factorization is suitable for recommending something when you have a dataset with only customer id and product id and the above sample I mentioned is exactly for that kind of dataset.

I'm going to show you a small chunk of my training dataset.

> [UserId] [ProductId] 
3　　　　1
3　　　　15
3　　　　23
5　　　　9
5　　　　1
8　　　　2
8　　　　1
.
.

I built a model upon the dataset and did exactly like the sample, _**changing the column name a bit and the training dataset itself**_. And it seems working great, but it just cannot deal with a new customer which didn't exist in the dataset, say customer id 1.

What should be done to recommend a list of products to the new customer? What should be added to the pipeline? should I retrain my model with the new customer's data? or should I take another way to do this?

**Comment by asthana86** [comment]
One Class Matrix Factorization does not take in other attributes like age, or gender which can be used to make recommendations for new users. However there are multiple ways to address a cold start or a new user issue. Following are few options. 

1. You can recommend a new user popular or most sold/popular products from your product catalog. 
2. Once a particular has selected an order item but perhaps not purchased it yet, you can take the action of carting or selecting that item as a hint for an item the user has purchased. 

Will either of these solutions work for your scenario?

**Comment by asthana86** [comment]
@wschin perhaps has some additional advice on this issue.

**Comment by prathyusha12345** [comment]
Closing as it is stale now. Please, re-open if needed further answers for your question.
