### ISSUE TITLE
How were these features calculated?

### ISSUE THREAD

**Issue by Infernogates** [dotnet/machinelearning-samples#193]
The file is in the following directory: machinelearning-samples/samples/csharp/end-to-end-apps/Regression-SalesForecast/src/eShopForecastModelsTrainer/data/countries.stats.csv

I tried training the model with only date and sales features recently and I noticed the predictions could be more precise if I used the rest of the features as well. I was just wondering how next, max, min, std, count and med features were calculated so I can make my own input data more detailed.

I have a test csv with data back to 2018 January, the last 7 lines are like following:

Next,Year,Month,Day,Qty,Avg,min,max,std,Total,Prev
204727.546,2018,12,31,455,552.5607121,0,0,0,251415.124,394623.098
180598.144,2019,1,1,344,595.1382151,0,0,0,204727.546,251415.124
184067.866,2019,1,2,314,575.1533248,0,0,0,180598.144,204727.546
148231.06,2019,1,3,296,621.8508986,0,0,0,184067.866,180598.144
287874.418,2019,1,4,272,544.9671324,0,0,0,148231.06,184067.866
266407.026,2019,1,5,519,554.6713256,0,0,0,287874.418,148231.06
138386.494,2019,1,6,489,544.7996442,0,0,0,266407.026,287874.418

I've put 0 to those features cause I have no idea how to calculate them
Next label is supposed to be prediction of Total of the next day.
Qty is how much items sold
Avg is the average price calculated from Total and Qty divided.
Total is the total sales price

At first I supplied the training pipeline with only date and total features then I tried adding Qty and Avg features as well but I didn't see a much difference in the predictions so like I said if I add more features like min,max,std maybe would it help making more accurate predictions?

Also I noticed FastTree trainer is making better predictions than FastTreeTweedie with the current features I'm using. Here's an output using FastTree Trainer:

*************************************************************************************************************
*       Metrics for Microsoft.ML.Trainers.FastTree.FastTreeRegressionTrainer Regression model
*------------------------------------------------------------------------------------------------------------
*       Average L1 Loss:    77167.34
*       Average L2 Loss:    10117625081.933
*       Average RMS:          77167.34
*       Average Loss Function: 10117624938.041
*       Average R-squared: 0.384
*************************************************************************************************************
Year: 2019, month: 1, day: 6 - Prediction (total): 262082.8 | Actual = 266407
Year: 2019, month: 1, day: 7 - Prediction (total): 189339.7 | Actual = 138386.4
Year: 2019, month: 1, day: 8 - Prediction (total): 176783.4 | Actual = 178393.58

I just have a feeling like I might been using this all in the wrong way so I thought it'd be best to ask out
Thanks

**Comment by asthana86** [comment]
@CESARDELATORRE

**Comment by asthana86** [comment]
@zeahmed can you perhaps help here with this issue.

**Comment by Infernogates** [comment]
Never mind, I solved the issue
