### ISSUE TITLE
"Weight" Column in regression trainer

### ISSUE THREAD

**Issue by HarshitShukla** [dotnet/machinelearning-samples#194]
I am working on the regression trainers for my Model.
I have to tell my model to take priority on a few numerical columns and then take the rest numerical column to predict some value. I tried searching for an example of weight. I haven't found any example of weight. Can you please send some example or how to solve the above problem using ML.Net.

If 'weight column' has some different purpose can you please explain it.
You can use my email 'harshit.shukla@medibuddy.in' If you require or convey any Information.

**Comment by asthana86** [comment]
@glebuk

**Comment by glebuk** [comment]
@HarshitShukla,
The weight parameter ML.NET refers to the column name containing the weight of the entire training example.  For example, if you have a list of customers to target for marketing campaign, you can mark their importance for prediction by giving higher weight for those that bring higher revenue.

What you are looking for is understanding what feature is more valuable to make correct prediction.  This is precisely the role of machine learning algorithm is to determine this from the data.  If you already know the weight for each feature, then you really do not need the machine learning.  Conversely, if you know some features are useless, you can excude them from training by removing them from the feature vector column,

Feel free to follow up in this thread if this does not answer your question.
Regards

**Comment by CESARDELATORRE** [comment]
Since it's been answered, I'm closing the issue for now. Re-open if needed. 👍
