### ISSUE TITLE
Column Weight For Multi Class Trainer

### ISSUE THREAD

**Issue by DevLob-zz** [dotnet/machinelearning-samples#199]
Hello All, 

is there is an example how to use Column Weight For Multi Class Trainer

best regards

**Comment by asthana86** [comment]
@glebuk

**Comment by glebuk** [comment]
I don't think we have an actual e2e sample currently.  The basic idea is that you need to have a column in your training data that contains a weight for each example of type float.  It would tell the learner how much importance to give to each training example.  For example, if example1 has weight = 2.0 and the rest have weight =1.0, then it is similar to having row1 appear twice.
In the code you just add an extra argument to the Estimator, such as:
```csharp
var reader = mlContext.Data.TextReader(new TextLoader.Arguments
        {
        Column = new[] {
            new TextLoader.Column("SentimentText", DataKind.Text, 1),
            new TextLoader.Column("Label", DataKind.Bool, 0),
            new TextLoader.Column("MyWeight", DataKind.R4, 2),
        },
        HasHeader = true,
        Separator = ","
});

...
.mlContext.Regression.Trainers.StochasticDualCoordinateAscent(
        labelColumn: "Label", 
        featureColumn: "SentimentVector", 
        weights: "MyWeight"));
...
```

Hope that helps!

**Comment by prathyusha12345** [comment]
Can you please open the issue in[ ML.Net repo](https://github.com/dotnet/machinelearning) as it is not related to samples. Thanks 👍
