### ISSUE TITLE
Mulit Task learning

### ISSUE THREAD

**Issue by Tak-Au** [dotnet/machinelearning-samples#207]
Question, Instead of predicting just one class out of all the classes.  Can we build one model that can predict if the data belongs to more than 1 class?

**Comment by DevLob-zz** [comment]
you can add this attribute in your prediction model class


        [ColumnName("Score")]
        public float[] Score { get; set; }

and this score array get prediction about all classes you train 

you can sort it and use it with your logic

**Comment by Tak-Au** [comment]
Don't believe this is what I am looking for unless I am missing something.
Looking at the Iris example, it's assumed that each data will only fall
into one of the classes.  However, for my input data, each item can fall
into more than 1 classes.  I can accomplish if I train multiple models,
each model being binary classification to each class. But I am hoping to
just have 1 model instead of multiple models.  No the end of the world.

**Comment by justinormont** [comment]
There is no direct support for multi-label tasks. You could get part-way there by running as a multi-class classification task.

The scores column for multi-class will give you some guess for all of the classes. But this is generally a normalized score vector in the form of, all the scores for the classes sum to 1.0 (one less degree of freedom). For your purpose, this normalization isn't helpful and the raw scores would be beneficial. 

You could simply threshold each of the scores in score vector to say which classes it belongs to. Treating this as a multi-class problem does require that your training labels have a single label, but when predicting the output vector is a prediction for each of the labels. There's no support for creating the output metrics (no multi-label evaluatator).

See also: https://github.com/dotnet/machinelearning/issues/807

**Comment by Tak-Au** [comment]
Thank you for the clarification.  As of now, I will be using multiple
models until such feature is supported.

Tak Au,
