### ISSUE TITLE
Adding MNIST Sample

### ISSUE THREAD

**Issue by sagar027** [dotnet/machinelearning-samples#209]
MNIST classification is a frequently used challenge for people starting up in machine learning domain, we would like to contribute a sample that uses Multiclass Logistic Regression for MNIST classification. We have a sample ready, which we wrote a while ago.
Disclosure : I & the co-contributor work for Microsoft

**Comment by CESARDELATORRE** [comment]
@sagar027 - Sure! It'd be great to add it as a sample for ML.NET.
If you create a PR we can review it and eventually merge it.
If it is a simple sample, just a console app for training, testing/evaluation and a simple try for scoring, you can add it to the "getting started" samples folder.

**Comment by sagar027** [comment]
@CESARDELATORRE  : Will do and update accordingly.
