### ISSUE TITLE
F# BikeSharing sample never ends training when running as F5 in Visual Studio

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning-samples#213]
The F# BikeSharingDemand sample has an issue (it also happens in C# for other samples if not using a workaround explained below).

Basically, in 0.9, the pipeline cache is not enabled by default (because of multiple reasons) and there's a related bug when you run the sample in VS with F5 (Debugging attached to process) where too many threads are created and the process never-ends...

The bug is explained in this issue I opened in the ML.NET repo: 
https://github.com/dotnet/machinelearning/issues/2099

Basically, the workaround is to explicitly enable the pipeline cache with this:

.AppendCacheCheckpoint(mlContext);

You might notice a lot of training perf improvement when using the cache, too, so you might want to add it to additional samples if it improves the training and test time. :)

However, this change has to be done directly into the pipeline. You don't have that method in the "ModelBuilder" helper class.

I would also recommend to step-out of the "ModelBuilder" helper class as we did in late November 2018 for the C# samples because these kind of code changes but mostly because we want developers to directly learn the ML.NET API. If using these helper classes, a developer might not clearly see how the ML.NET API is shaped.. This is specially important for the pipeline-chain API.

**Comment by mariuszwojcik** [comment]
@CESARDELATORRE thanks for info, I will look into this in the next few days.

And regarding 'ModelBuilder' helper module - makes sense! Will move the code into relevant functions.

**Comment by kevmal** [comment]
I think this issues has been resolved

**Comment by prathyusha12345** [comment]
Closing this issue. 
Thanks :)

@CESARDELATORRE Adding for referrence
