### ISSUE TITLE
how to train new data on the original model,and  upgrade it 

### ISSUE THREAD

**Issue by debin168** [dotnet/machinelearning-samples#215]
for example, As data continue to grow ,the old model is not suit  the new data,should i train the new model by all data?  does anyway i just need to train the new data  with old model?   any sample or ml.net api document to learn?

**Comment by CESARDELATORRE** [comment]
You need to train again with the new data which the creates a new model.
Re-training on top of an existing model is a lot more complex and in many cases you cannot do it in ML.NET

**Comment by CESARDELATORRE** [comment]
Closing the issue. Re-open if needed, ok? 👍
