### ISSUE TITLE
HeartPrediction sample Accuracy is low (0.25) - Increase training dataset's volume?

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning-samples#224]
@MarcoZama - Marco, the HeartPrediction sample Accuracy is pretty low (0.25).
Could you increase the volume of the datasets or tune the trainer so we get a higher accuracy?

![image](https://user-images.githubusercontent.com/1712635/52155154-2c9bac80-2636-11e9-95a8-a11496524a91.png)

**Comment by MarcoZama** [comment]
@justinormont, @CESARDELATORRE about the dataset i also saw that it was boolean. But after in the cleveland dataset processed i understand it was multiclass. Is a mistake? 
@CESARDELATORRE I didn't receive notification for that issue, sorry for my delay.

**Comment by CESARDELATORRE** [comment]
@MarcoZama - Are you going to try to improve the approach?

**Comment by justinormont** [comment]
@MarcoZama: Yes, the label should be binary.

**Comment by MarcoZama** [comment]
Ok i’ll Try!

**Comment by prathyusha12345** [comment]
@MarcoZama I removed this sample currently from machineLearning-samples repo. Please send the PR once the sample is ready with the Binary Classification.
