### ISSUE TITLE
Question : Predict Using some of training Features

### ISSUE THREAD

**Issue by DevLob-zz** [dotnet/machinelearning-samples#229]
Hello 

i have a question is there is a way to train a model using for example 10 features 

and then while i predicting i select for example 4 features only to predict according to them  instead of 10 features

**Comment by CESARDELATORRE** [comment]
Afaik, no. 
You can train a model using many variables, but then, all of them will be taken into account when scoring.
 If you want to include a different set of variables, you'll need to create a different model for that.
The prediction engine doesn't allow to select and use different sets of variables when predicting.
Afaik, scoring that way with just a subset of columns (using the same model) is also NOT possible when using something comparable like Scikit-Learn in Python. I might be wrong, but I haven't seen that in Scikit-Learn, neither.

**Comment by DevLob-zz** [comment]
Thanks ,

but what if i have same data and need to generate different models with different features that load from database currently there is no way to implement this when data load from database

is the integrated with database will be fully supported soon ?

best regards

**Comment by DevLob-zz** [comment]
I think it can handled within 
//After create the IDataView  object i can then select which columns will be using to predict the value 
`  IDataView dataView = mlContext.Data.LoadFromEnumerable(noramalTagsTrainingData);
   
         var pipeline = mlContext.Transforms.SelectColumns(features);
            IDataView filtterdView = pipeline.Fit(dataView).Transform(dataView);
            return filtterdView;`
