### ISSUE TITLE
ML.net 0.10.0 upgrade of MulticlassClassification Model

### ISSUE THREAD

**Issue by vickyrathee** [dotnet/machinelearning-samples#247]
I was learning ML [using this sample code available](https://github.com/zubialevich/BbcNewsClassifier) to classify news, which was working fine on old nuget package. But I just upgraded to latest version and everything broken. So, I was trying to upgrade my code as per below. But seems like I am still missing something and getting schema mismatch error. Any advise?

**ArgumentOutOfRangeException**

`Schema mismatch for label column 'Label': expected float, double or KeyType, got TextParameter name: labelCol`

**Trainer**

```
private static ITransformer BuildTrainEvaluateAndSaveModel(MLContext mlContext)
{
	// STEP 1: Common data loading configuration
	IDataView trainingDataView = mlContext.Data.ReadFromTextFile<NewsData>(trainingSet, hasHeader : false, supportSparse : false);
	
	IDataView testDataView = mlContext.Data.ReadFromTextFile<NewsData>(testSet, hasHeader : false, supportSparse : false);

	// STEP 2: Common data process configuration with pipeline data transformations          
	var dataProcessPipeline = mlContext.Transforms.Text.FeaturizeText(outputColumnName: DefaultColumnNames.Features, inputColumnName: nameof(NewsData.Text));
	
	// STEP 3: Set the training algorithm, then create
	
	var trainer = mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent(labelColumn: DefaultColumnNames.Label, featureColumn: DefaultColumnNames.Features);
	var trainingPipeline = dataProcessPipeline.Append(trainer);

	// STEP 4: Train the model fitting to the DataSet
	Console.WriteLine("=============== Training the model ===============");
	ITransformer trainedModel = trainingPipeline.Fit(trainingDataView);

	// STEP 5: Evaluate the model and show accuracy stats
	Console.WriteLine("===== Evaluating Model's accuracy with Test data =====");
	var predictions = trainedModel.Transform(testDataView);
	var metrics = mlContext.MulticlassClassification.Evaluate(data: predictions, label: DefaultColumnNames.Label, score: DefaultColumnNames.Score);
	
	// STEP 6: Save/persist the trained model to a .ZIP file
	using (var fs = new FileStream(modelPath, FileMode.Create, FileAccess.Write, FileShare.Write))
		mlContext.Model.Save(trainedModel, fs);

	Console.WriteLine("The model is saved to {0}", modelPath);

	return trainedModel;
}
```

Model, data etc is [all here on Github sample](https://github.com/zubialevich/BbcNewsClassifier)

**Comment by DevLob-zz** [comment]
try this 
 var trainingPipeline = mlContext.Transforms.Conversion.MapValueToKey(DefaultColumnNames.Label)
               .Append(dataProcessPipeline)
               .Append(mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent(labelColumn: DefaultColumnNames.Label, featureColumn: DefaultColumnNames.Features))
               .Append(mlContext.Transforms.Conversion.MapKeyToValue(DefaultColumnNames.PredictedLabel));

  trainedModel = trainingPipeline.Fit(trainingDataView);

**Comment by DevLob-zz** [comment]
mlContext.Transforms.Conversion.MapValueToKey(DefaultColumnNames.Label)

**Comment by vickyrathee** [comment]
Thanks @DevLob-zz it works. Does the Score[] displayed alphabetically for each category? and should be good if I map the category names from alphabetical category list, if need to show Top 2 or Top (n) best guess. 

Or is there way to populate all category names as well along with Score in result. This is how the result looks like for :  "UK young top Euro earnings league British children enjoy the highest average annual income in Europe". So looks like alphabetical in this case.

![image](https://user-images.githubusercontent.com/6106479/52531473-f350f400-2d3b-11e9-892a-c8e93478cd7e.png)

**Comment by DevLob-zz** [comment]
> Thanks @DevLob-zz it works. Does the Score[] displayed alphabetically for each category? and should be good if I map the category names from alphabetical category list, if need to show Top 2 or Top (n) best guess.
> 
> Or is there way to populate all category names as well along with Score in result. This is how the result looks like for : "UK young top Euro earnings league British children enjoy the highest average annual income in Europe". So looks like alphabetical in this case.
> 
> ![image](https://user-images.githubusercontent.com/6106479/52531473-f350f400-2d3b-11e9-892a-c8e93478cd7e.png)

in the previous versions there is a method that i used to get the Labels name but for some reason this is removed 
string[] scoreLabels;
model.TryGetScoreLabelNames(out scoreLabels);

**Comment by DevLob-zz** [comment]
![image](https://user-images.githubusercontent.com/5037612/52531881-0ad0b280-2d25-11e9-8fb8-ef3f63ed183a.png)
this may be valid workaround if there is non direct access for that

**Comment by vickyrathee** [comment]
thanks very much. Would you be able to help in [this one on Stackoverflow](https://stackoverflow.com/questions/54593082/simple-sentiment-analysis-using-ml-net-and-ienumerable-dataview) as well using `IEnumerable DataView`. I am not able to find a solution from couple of days to make a simple sentiment analysis using an array. Or let me know if you want me to open a new thread here?

**Comment by marcKoutzarov** [comment]
`  Console.WriteLine("Create a ML.NET environment");
           MLContext mlContext = new MLContext();
           IDataView trainingDataView = mlContext.Data.LoadFromTextFile<ModelClass>(path: "KYCRiskModel.csv", hasHeader:false, separatorChar: ',');


            Console.WriteLine("Transform your data and add a learner...");
            var pipeline2 = mlContext.Transforms.Conversion.MapValueToKey("Label")
            .Append(mlContext.Transforms.Concatenate("Features", "FirstName", "MiddleName", "LastName", "Email", "Mobile", 
            "Address", "IdDocument", "SanctionList_Hit", "WatchList_Hit", "PEPList_Hit", "SanctionList_Check", 
            "WatchList_Check", "PepList_Check", "BankAccount"))
            .AppendCacheCheckpoint(mlContext)
            .Append(mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent(labelColumnName: "Label", featureColumnName:"Features",))
            .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));

          
            Console.WriteLine("Training model based on the data set");
            var model = pipeline2.Fit(trainingDataView);

            Console.WriteLine("Saving trained model....");
            var path = "trainedModel.zip";
            using (FileStream fs = File.Create(path))
            {
                mlContext.Model.Save(model, fs);
            }


            Console.WriteLine("Testing the trained model");
            var Customer = new ModelClass
            {
               Address = 1f,
              
               Email = 1f,
               Mobile = 1f,
               FirstName =1f,
               IdDocument =1f,
               LastName = 1f,
               MiddleName =1f,
               BankAccount = 1f,
               PepList_Check =1f,
               SanctionList_Check=1f,
               WatchList_Check=1f,

               PEPList_Hit=0,
               SanctionList_Hit=1,
               WatchList_Hit=0,
            };

            Console.WriteLine("");
            var prediction = model.CreatePredictionEngine<ModelClass, ModelPrediction>(mlContext).Predict(Customer);
            Console.WriteLine($"Predicted riskFactor is: {prediction.PredictedLabels}");
           
            Console.WriteLine("");`

**Comment by prathyusha12345** [comment]
Hoping that this issue is resolved. Closing the issue. Thanks 👍
