### ISSUE TITLE
Product recommendation sample

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning-samples#249]
I would suggest to create const MaxId
`private  const long MaxId = 262111;`
and use it across whole file https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/MatrixFactorization_ProductRecommendation/ProductRecommender/Program.cs and add comment what it should be (maximum id value in file +1). 
Any Id which is above or equal to that value would be ignored.
Otherwise users will just bring their dataset and would be upset that it doesn't work like here: https://github.com/dotnet/machinelearning/issues/2488

**Comment by wschin** [comment]
As https://github.com/dotnet/machinelearning/issues/2488 had been fixed, may we close this issue?

**Comment by prathyusha12345** [comment]
Sure @wschin
