### ISSUE TITLE
[Enhancement] Use NameOf for References to columns in all samples

### ISSUE THREAD

**Issue by dan-drews** [dotnet/machinelearning-samples#25]
Hi!

I noticed in the [eShopForecastModelsTrainer](https://github.com/dotnet/machinelearning-samples/blob/master/samples/end-to-end-apps/eShopDashboardML/src/eShopForecastModelsTrainer/ProductModelHelper.cs) that the code uses `NameOf(model.property)` for all of the column references. 

I think this is a great idea and I'm wondering if that should be an encouraged pattern by updating all of the existing samples to follow that pattern.

**Comment by CESARDELATORRE** [comment]
Closing this issue as it is stale since it was related to the deprecated LearningPipeline API.
We're moving to the new Dynamic API.
