### ISSUE TITLE
documentation on MulticlassClassification_Iris should explain the score array

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning-samples#250]
Hi,

I think that the documentation for the multiclasifier could be enhanced to show how to map the score[index] to the proximity of the enum/ label predicted, this might not be clear when reading the code. 

Also one could/should mention that the enum should not have flags and must be of type uint as we have an "negative -neutral- positive" scaled enum and it doesn't like negative enum values.     

Peter.

**Comment by DevLob-zz** [comment]
it was exist before 0.10 for some reason remove but i think will redo in 0.11 as i show the progress for the next following this is one of the done tasks so you need to wait for the next releases 0.11 in few days

**Comment by CESARDELATORRE** [comment]
@DevLob-zz - What documentation in particular you are referring to? (before 0.10 and targeting 0.11).
Can you point to the PR or any resource you mean?

**Comment by CESARDELATORRE** [comment]
@prathyusha12345 - You are also working on a sample related to this (labels related to scores) updating the GitHub issues classification sample. 
Can you also explain/update a bit better the documentation/readme.md for MulticlassClassification_Iris, as well?

**Comment by DevLob-zz** [comment]
> @DevLob-zz - What documentation in particular you are referring to? (before 0.10 and targeting 0.11).
> Can you point to the PR or any resource you mean?

as i remember the prediction engine was have 
TryGetScoreLabelNames(out NormalTagsPrediction.scoreLabels)

i see you added it to be done in 0.11
https://github.com/dotnet/machinelearning/issues/2233

**Comment by PeterPann23** [comment]
Please note that the iris model does not specifically define a label column and does not normalize. Perhaps the documentation should mention the reasoning behind this as it is a deviation on the other samples.

**Comment by prathyusha12345** [comment]
@CESARDELATORRE Ok I will add more details to it and update the details here once done.

**Comment by prathyusha12345** [comment]
I have added the code and comments related to the code here https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/MulticlassClassification_Iris/IrisClassification/IrisClassificationConsoleApp/Program.cs.

Basically we map the label to key column while preparing data and while predicting we retrieve the labels using key columns. .

Closing this issue. Please reopen if you still need more details.

Thanks 👍

**Comment by PeterPann23** [comment]
Yes, I have seen the change, perhaps add the documentation stating that one can also use the value and not the order by specifying the optional ValueToKeyMappingEstimator.SortOrder parameter in rel 0.11 or the ValueToKeyMappingEstimator.KeyOrdinality in 1.0 release respectively
