### ISSUE TITLE
Movie Recommendation metrics RMS and RSquared = 0

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-samples#256]
In the Movie Recommendation sample with the MatrixFactorizationTrainer, when I uncomment line 60 in Program.cs, the rms is 0. Same for RSquared.

//Console.WriteLine("The model evaluation metrics rms:" + Math.Round(float.Parse(metrics.Rms.ToString()), 1));)

**Comment by prathyusha12345** [comment]
I checked this issue in v0.9 and it occurs in v0.9 as well. The metrics value shows as 0 for everything as shown below.

![image](https://user-images.githubusercontent.com/22335043/52887508-cda55f80-312c-11e9-9382-c50acad02b57.png)

Let me check this with Ankit and get back to you.

**Comment by kevmal** [comment]
The problem is with `ReadFromTextFile`for `testDataView`. The separator is missing so the data is not loading properly.

**Comment by prathyusha12345** [comment]
@Kevin Malenfant ,thanks for identifying the problem. I will fix it and push.
