### ISSUE TITLE
HeartDisease sample may be consfusing

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning-samples#258]
Hi,

The code:
```
var trainingDataView = mlContext.Data.ReadFromTextFile<HeartDataImport>(path:TrainDataPath, hasHeader: true, separatorChar: ',');
            var testDataView = mlContext.Data.ReadFromTextFile<HeartDataImport>(path:TestDataPath, hasHeader: true, separatorChar: ',');

```
claims that the training data contains a header however the data files in the Data folder do not. It also does not contain a label column, guess that this is why the last column is used.

the following code:
```
            foreach (var heartData in HeartSampleData.heartDatas)
            {
                var prediction = predictionEngine.Predict(heartData);

                Console.WriteLine($" 0: {prediction.Score[0]:0.###}");
                Console.WriteLine($" 1: {prediction.Score[1]:0.###}");
                Console.WriteLine($" 2: {prediction.Score[2]:0.###}");
                Console.WriteLine($" 3: {prediction.Score[3]:0.###}");
                Console.WriteLine($" 4: {prediction.Score[4]:0.###}");
                Console.WriteLine();
            }
```
Also it claims to diagnose a particular disease however it contains no mapping to the disease mapped & predicted. Having a % of Disease 1 does not provide much inside on the actual quality of the prediction. 

In the Iris sample the data is sorted, classes are ordered in a given way and therefore result 1 perhaps maps to the correct species (class order is based on the order data is seen "saw one before the other" as described in [KeyValues](https://github.com/dotnet/machinelearning/blob/master/docs/code/KeyValues.md). 
the % then states how certain it is that the prediction is accurate.

The % approach when it comes to diseases is the correct one as one could have several at the same time, where as one could be only 1 type of Iris. 

Perhaps demonstrate consider mapping disease one to a dictionary or enum value, an enum would be nice as one could flag them for further testing when the % is above a threshold.

**Comment by CESARDELATORRE** [comment]
Closing this issue. We removed this sample as there were other additional issues with it.
