### ISSUE TITLE
F# CreditCard Fraud Detection Sample is showing accuracy as 1 in metrics

### ISSUE THREAD

**Issue by prathyusha12345** [dotnet/machinelearning-samples#263]
@kevmal The F# Credit card fraud detection sample shows accuracy as 1. Please see the below output when running the F# sample
![image](https://user-images.githubusercontent.com/22335043/53188653-b5b15e00-35ba-11e9-90e5-a06718277df9.png)

Expected result (What you get with the C# sample):
-----------------
![image](https://user-images.githubusercontent.com/22335043/53188696-ceba0f00-35ba-11e9-8544-9de885163fbb.png)

**Comment by CESARDELATORRE** [comment]
@kevmal - Thanks for your contributions. When possible it would be great if you can fix this issue in the F# sample. 👍

**Comment by prathyusha12345** [comment]
Below PR is having Fix https://github.com/dotnet/machinelearning-samples/pull/268
