### ISSUE TITLE
IRISCLassification accuracy is showing as 1 which is incorrect.

### ISSUE THREAD

**Issue by prathyusha12345** [dotnet/machinelearning-samples#280]
@CESARDELATORRE  The accuracy value came as 1 while evaluating IRISClassification sample. I checked if ### **train** and **test** data sets are having any common rows. I found only 2 rows are common. i removed them from **Test dataset** and checked. Still the accuracy is showing as 1.Can we test the sample with other data if there is any problem in actual data?

Sample: https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MulticlassClassification_Iris

**Comment by CESARDELATORRE** [comment]
Closing for now. This is due to the fact that the dataset is pretty small. But the code implementation is right.
