### ISSUE TITLE
Broken image link in Fraud Detection sample README

### ISSUE THREAD

**Issue by natke** [dotnet/machinelearning-samples#283]
URL: https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection

Link: https://raw.githubusercontent.com/dotnet/machinelearning-samples/features/samples-new-api/samples/csharp/getting-started/shared_content/modelpipeline.png

Should be: ../shared_content/modelpipeline.png

**Comment by prathyusha12345** [comment]
@natke I am working with @CESARDELATORRE. I have added a comment to update to absolutepath/fullpath  in the PR. Could you please look at it.

**Comment by natke** [comment]
Hi @prathyusha12345,  I can't see your comment in the PR.

**Comment by prathyusha12345** [comment]
@natke Please check now.
