### ISSUE TITLE
BikeSharingDemand is still using ML.NET 0.2.0

### ISSUE THREAD

**Issue by dsyme** [dotnet/machinelearning-samples#29]
Just to mention that the sample

    samples\examples\Reggression_BikeSharingDemands\BikeSharingDemand

is still using ML.NET 0.2.0.

**Comment by CESARDELATORRE** [comment]
Thanks for the heads-up. Upgraded now to ML.NET v0.3 or any version which is globally specified with $(MicrosoftMLVersion) from the global Directory.Build.props file, with this PR:
ttps://github.com/dotnet/machinelearning-samples/pull/31

Closing the issue.
