### ISSUE TITLE
Website link pointing to incorrect sample

### ISSUE THREAD

**Issue by natke** [dotnet/machinelearning-samples#291]
The Price Prediction scenario points to the Movie Recommendation sample on: https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet

i.e. both of the samples in the attached screenshot link to the same location

<img width="887" alt="screen shot 2019-03-02 at 8 30 46 am" src="https://user-images.githubusercontent.com/3302433/53684709-84751400-3cc5-11e9-98f7-f348c775a68a.png">

**Comment by prathyusha12345** [comment]
@CESARDELATORRE  As I am not working on this, Can you let me know who owns the code/repo for this page

**Comment by CESARDELATORRE** [comment]
@rowanmiller - Please close this issue when fixed. 👍

**Comment by rowanmiller** [comment]
Fixed

**Comment by rowanmiller** [comment]
This is fixed. I don't have permission to close the issue if @prathyusha12345 or @CESARDELATORRE  can dot it 😄.

**Comment by CESARDELATORRE** [comment]
Closed! Thanks a lot Rowan! 👍
