### ISSUE TITLE
[README.MD] Missing link in home page to one Recommender sample

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning-samples#292]
@prathyusha12345 

We have three samples. One is missing in the home page.
![image](https://user-images.githubusercontent.com/1712635/53687436-7a650c80-3ce9-11e9-9170-7bb30b9684b2.png)

Thanks,

**Comment by prathyusha12345** [comment]
@CESARDELATORRE As discussed we have 3 samples. You might have figured incorrectly as Movie Recommendation samples are in same row.
1. Movie Recommnedation -Console
2. Movie Recommendation - web
3. Product Recommendation -console
