### ISSUE TITLE
[README.MD] In 0.11 branch-work in progress, review update readme for FraudDetection so it aligns with the new code 

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning-samples#293]
Need review update readme for FraudDetection so it aligns with the new code I updated to 0.11. It is also refactored/simplified significantly, so README.MD needs to be updated:

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection

**Comment by prathyusha12345** [comment]
@CESARDELATORRE As discussed we have 3 samples. You might have figured incorrectly as Movie Recommendation samples are in same row.
1. Movie Recommnedation -Console
2. Movie Recommendation - web
3. Product Recommendation -console
