### ISSUE TITLE
Adding F# samples

### ISSUE THREAD

**Issue by dsyme** [dotnet/machinelearning-samples#30]
I'm looking at adding some initial F# samples

Should the pivot be 
    samples\CSharp\getting-started\BinaryClassification_SentimentAnalysis 
    samples\FSharp\getting-started\BinaryClassification_SentimentAnalysis 
   or 
    samples\getting-started\BinaryClassification_SentimentAnalysis\CSharp
    samples\getting-started\BinaryClassification_SentimentAnalysis\FSharp

I don't mind either way. The former is probably better

* PRO: you choose a language, then you get the sample set

* PRO: if community provide samples they are likely to be in one language

* CON: it means the sample sets are more likely  will diverge over time

* PRO: if samples are missing for one language it doesn't really matter, you don't really notice

**Comment by dsyme** [comment]
cc @asthana86

**Comment by dsyme** [comment]
The F# getting-started samples are added in https://github.com/dotnet/machinelearning-samples/pull/32 with the pivot at the top, let's discuss there

**Comment by isaacabraham** [comment]
@dsyme should i close #7 now?

**Comment by dsyme** [comment]
@isaacabraham Ah sorry, I didn't even notice #7.  Yes, I suppose close it. Could you move the info about ionide into my PR though?
