### ISSUE TITLE
Question [Table Structure Recognizer ]

### ISSUE THREAD

**Issue by DevLob-zz** [dotnet/machinelearning-samples#300]
Dear all

is there is a way if i have multiple PDF Document and need to convert it to HTML Tagged Pages 

for example 

to recognize table structure within ML 
![image](https://user-images.githubusercontent.com/5037612/53935880-a51be000-40b0-11e9-8b4f-86ecd617a641.png)
![image](https://user-images.githubusercontent.com/5037612/53935886-a947fd80-40b0-11e9-801e-011d34d83140.png)
![image](https://user-images.githubusercontent.com/5037612/53935986-017eff80-40b1-11e9-8416-b9cee27b46fe.png)
![image](https://user-images.githubusercontent.com/5037612/53936029-2c695380-40b1-11e9-85e6-b839249327c6.png)

learn module that this structure should be a table and structure will be as learning or just recognize the table pattern within ML.net   

if i have another table "with pre-learning Pattern" have a different data and information  
can i still recognize it 

best regards

**Comment by CESARDELATORRE** [comment]
You can use Binary Classification or multi-class classification when providing single pieces of text (like in the GitHub issues classification) and if you have many pieces of labeled text/data saying this kind of text is an HTML-Table, you could predict afterwards.

The issue I see is that you need to provide specific pieces of text and ask/predict about it.
I don't initially see how you could provide a whole PDF document to ML.NET... you'd need to prepare the text data first. in multiple pieces.

 What would be challenging is what concrete pieces of text you provide to ML.NET. Per page? Then ML.NET can tell you if there's a table in that page?

The scenario is not clear for me..

**Comment by DevLob-zz** [comment]
I think this will not be useful ,
as the whole page may contain another data , component's 
i need first from page energy for example to detect where is the bounding box of the table and then from ML Extract other feature who cell be arrange within the table , and how row , col Span will be id there is a way to learn my model by this way 
best regards 

in DL there is some thing called 
"specific-entity-extraction-from-unstructured-text"

**Comment by prathyusha12345** [comment]
Can you please open the issue in [ML.Net Repo](https://github.com/dotnet/machinelearning) as this is not related to Samples.
