### ISSUE TITLE
pippo

### ISSUE THREAD

**Issue by maionegianni61** [dotnet/machinelearning-samples#303]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/dataset
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by prathyusha12345** [comment]
What kind of problem did you encounter?
Can you provide further details, exceptions, etc.?

**Comment by prathyusha12345** [comment]
Closing this issue. Please reopen if you encounter any issue. Thanks
