### ISSUE TITLE
what is the equivalent of FeaturizeText in python?

### ISSUE THREAD

**Issue by 1amirjalai** [dotnet/machinelearning-samples#309]
i'm curious to know that what is the equivalent of FeaturizeText in python?
could someone please convert this sample to python?

**Comment by CESARDELATORRE** [comment]
What sample do you mean? In any case, we're the .NET team, so we'd like to promote .NET and ML.NET not Python. ;)
In any case, a similar/equivalent APIs to encode text in Python could be any of the following depending on the case and type of column (you'll need to research Scitkit-Learn for those cases):

- CountVectorizer 
- OneHotEncoder
- CategoricalEncoder
- LabelEncoder

Closing the issue as it is not related to our samples in ML.NET, ok? :)

**Comment by 1amirjalai** [comment]
@CESARDELATORRE In my opinion ml.net is fantastic. on the other hand python is dominant in ml world for now. so there are many python codes which need to be ported to ml.et.
so on recommender system using Field Aware Factorization Machines FFM [Here](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Recommendation-MovieRecommender) i find out it uses FeaturizeText  for useruid  and movieid which both are categorical data [Here](https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender_Model/Program.cs).
So i wanna know the equivalent of FeaturizeText in python

**Comment by CESARDELATORRE** [comment]
Since useruid and movieid are categorical values, I'd say that in Python you'd use the CategoricalEncoder class which is only available since Scikit-Learn 0.20.

However, there are multiple ways to encode categorical values in Python. See this post, for example:
https://pbpython.com/categorical-encoding.html 

Thanks for the feedback! 👍

**Comment by 1amirjalai** [comment]
@CESARDELATORRE  thank you for your informative reply. i did some reading and i think  what [FeaturizeText ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.textcatalog.featurizetext?view=ml-dotnet) is doing is bag of words on userid and movieid am i right?
