### ISSUE TITLE
ml.net build errors 

### ISSUE THREAD

**Issue by chonseyt** [dotnet/machinelearning-samples#313]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/code
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.im getting build errors with this code using Microsoft.Data.DataView;
using Microsoft.ML;
using Microsoft.ML.Data;
using System;

// CS0649 compiler warning is disabled because some fields are only 
// assigned to dynamically by ML.NET at runtime
#pragma warning disable CS0649

namespace myApp
{
    class Program
    {
        // STEP 1: Define your data structures
        // IrisData is used to provide training data, and as
        // input for prediction operations
        // - First 4 properties are inputs/features used to predict the label
        // - Label is what you are predicting, and is only set when training
        public class IrisData
        {
            [LoadColumn(0)]
            public float SepalLength;

            [LoadColumn(1)]
            public float SepalWidth;

            [LoadColumn(2)]
            public float PetalLength;

            [LoadColumn(3)]
            public float PetalWidth;

            [LoadColumn(4)]
            public string Label;
        }

        // IrisPrediction is the result returned from prediction operations
        public class IrisPrediction
        {
            [ColumnName("PredictedLabel")]
            public string PredictedLabels;
        }

        static void Main(string[] args)
        {
            // STEP 2: Create a ML.NET environment  
            MLContext mlContext = new MLContext();

            // If working in Visual Studio, make sure the 'Copy to Output Directory'
            // property of iris-data.txt is set to 'Copy always'
            IDataView trainingDataView = mlContext.Data.LoadFromTextFile<IrisData>(path: "iris-data.txt", hasHeader: false, separatorChar: ',');

            // STEP 3: Transform your data and add a learner
            // Assign numeric values to text in the "Label" column, because only
            // numbers can be processed during model training.
            // Add a learning algorithm to the pipeline. e.g.(What type of iris is this?)
            // Convert the Label back into original text (after converting to number in step 3)
            var pipeline = mlContext.Transforms.Conversion.MapValueToKey("Label")
                .Append(mlContext.Transforms.Concatenate("Features", "SepalLength", "SepalWidth", "PetalLength", "PetalWidth"))
                .AppendCacheCheckpoint(mlContext)
                .Append(mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent(labelColumnName: "Label", featureColumnName: "Features"))
                .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));

            // STEP 4: Train your model based on the data set  
            var model = pipeline.Fit(trainingDataView);

            // STEP 5: Use your model to make a prediction
            // You can change these numbers to test different predictions
            var prediction = model.CreatePredictionEngine<IrisData, IrisPrediction>(mlContext).Predict(
                new IrisData()
                {
                    SepalLength = 3.3f,
                    SepalWidth = 1.6f,
                    PetalLength = 0.2f,
                    PetalWidth = 5.1f,
                });

            Console.WriteLine($"Predicted flower type is: {prediction.PredictedLabels}");

            Console.WriteLine("Press any key to exit....");
            Console.ReadLine();
        }
    }
}

**Comment by prathyusha12345** [comment]
@chonseyt  I don't understand the error where you are getting. Could you please specify it clearly

**Comment by ThomasFredLungu** [comment]
![Screenshot (59)](https://user-images.githubusercontent.com/35762539/54473697-df3d5e00-47e3-11e9-8b91-d3e09f39e1d1.png)

**Comment by CESARDELATORRE** [comment]
What's the specific error you are getting when compiling?
Are you using ML.NET v0.11 NuGet package?

**Comment by ThomasFredLungu** [comment]
![Screenshot (60)](https://user-images.githubusercontent.com/35762539/54481780-f01cbc80-4841-11e9-8d09-5a74d1ba6423.png)

hope you can see that image clearly. these are the errors  I am getting

**Comment by CESARDELATORRE** [comment]
Are you using the ML.NET **0.11** NuGet package? Either added like the following from the CLI or by using Visual Studio?:

`dotnet add package Microsoft.ML --version 0.11.0`

Looks like if you were using ML.NET **0.10.0** or previous where that LoadFromTextFile() method was named differently..

You can compare your code and project with this one available at the samples repo which compiles and works properly:

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/BinaryClassification_SentimentAnalysis

Hope that helps.

**Comment by chonseyt** [comment]
I keep getting this error error: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackagesFallback\' doesn't exist.

Sent from Mail for Windows 10

**Comment by chonseyt** [comment]
I figured it out thanks for your help

Sent from Mail for Windows 10

**Comment by CESARDELATORRE** [comment]
Closing issue.
