### ISSUE TITLE
unnecessary step in the tutorial

### ISSUE THREAD

**Issue by GeXiaoguo** [dotnet/machinelearning-samples#316]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/dataset
Operating System: windows

The tutorial runs the console app with "dotnet run" in the step that follows this one.  dotnet run by default uses the project folder as the working directory. This means copying the iris-data.txt file to the output directory is not necessary.

**Comment by CESARDELATORRE** [comment]
@GeXiaoguo - The tutorial specifies that you need to do that step only if you are using Visual Studio (not when using "dotnet run"), since in that case the path is different. 
So I don't think that step is wrong, right?

Closing the issue for now. Thanks for the feedback in any case! 👍
