### ISSUE TITLE
iris flower ML, i ran into two errors when developing this model

### ISSUE THREAD

**Issue by ThomasFredLungu** [dotnet/machinelearning-samples#317]
![Screenshot (59)](https://user-images.githubusercontent.com/35762539/54473745-a8b41300-47e4-11e9-9fdf-e9b52543c85f.png)
![Screenshot (60)](https://user-images.githubusercontent.com/35762539/54473754-be293d00-47e4-11e9-8a39-f6447164e1dd.png)

**Comment by jwood803** [comment]
What version of ML.NET are you using?

**Comment by prathyusha12345** [comment]
@ThomasFredLungu Please try using version ML.NET v0.11 and let me know if still face the issue.

Thanks @jwood803  for interacting.

**Comment by prathyusha12345** [comment]
If you are not facing issue after changing to ML.Net 0.11 I will close the issue.

Please reopen if you encounter again, ok?
Thanks
