### ISSUE TITLE
SentimentIssue.cs Text filed should load column 2 instead of 1

### ISSUE THREAD

**Issue by CodArs-van** [dotnet/machinelearning-samples#319]
Text field is used to retrieve the data from wikiDetoxAnnotated40kRows.tsv's column 'comment', which is column 2 of the tabular dataset, the source code set it to be 1, then it's not using 'comment' anymore but instead, the rev id. To make it right, we need to change it to 2.

**Comment by CodArs-van** [comment]
Change it to
```csharp
[LoadColumn(2)]
public string Text { get; set; }
```

**Comment by prathyusha12345** [comment]
@CodArs-van Thanks for catching this. I have fixed it here  https://github.com/dotnet/machinelearning-samples/commit/3cc7a9b881e2e75c409d6653b2719040edda2fc5

@CESARDELATORRE adding for reference.

Closing the issue. thanks
