### ISSUE TITLE
Training from database using a datatable without custom class

### ISSUE THREAD

**Issue by MeTTaxa** [dotnet/machinelearning-samples#323]
In a normal operationalized enterprise enviroment you can't really do an update of the software and the custom class each time a new feature is added.

We use sql server machine learning services with microsoftml for hundreds of models and we would like to migrate to ml.net however we need a way to add the training features dynamically without a strongly typed custom class.

Is there any way to use the datatable populated from sql server to be used directly without needing to create a strongly typed class for each model and a column each feature?

**Comment by CESARDELATORRE** [comment]
Can you open this same issue/question but on the [ML.NET repo issues](https://github.com/dotnet/machinelearning/issues) so the whole ML.NET team can get your feedback directly?

Issues here are more related to the ML.NET samples themselves.
I think your feedback is important to have it where it can be taken into account by the whole team.

About your question, you can Load data from a file without using a typed class, with 
            mlContext.Data.LoadFromTextFile(path, columns);

But you still need to provide the columns, not in a class but in code, at the end of the day. 

You will need the typed classes when creating the PredictionEngine, though, when scoring.

In a different page, if loading data from a database, the simplified steps are like the following:

```
// Let's assume that 'GetChurnData()' fetches and returns the training data from somewhere.

IEnumerable<CustomerChurnInfo> churnData = GetChurnInfo();

```
// Step one: load the data as an IDataView.
// Let's assume that 'GetChurnData()' fetches and returns the training data from somewhere.

var trainData = mlContext.Data.LoadFromEnumerable(churnData);
```

But in that case you still need a typed class like CustomerChurnInfo to load the data.

Please, submit this same issue to the [ML.NET repo issues](https://github.com/dotnet/machinelearning/issues) so the team analyzes other possible workarounds or improvements in our API. 👍

**Comment by prathyusha12345** [comment]
Closing the issue here. Thanks :)
