### ISSUE TITLE
Object Detection

### ISSUE THREAD

**Issue by turowicz** [dotnet/machinelearning-samples#335]
It would be nice to be able to migrate from TensorflowSharp to ML.NET. 

Can anyone fill in the Object Detection example?

**Comment by prathyusha12345** [comment]
@turowicz we are working on object detection sample. It will be available in repo in couple of days.

**Comment by turowicz** [comment]
@prabhat00155 perfect, please keep me posted.

**Comment by turowicz** [comment]
@prabhat00155 it will still run on GPU if I have my tensorflow compiled the right way?

**Comment by prathyusha12345** [comment]
@prabhat00155 I am not sure about TensorFlow for object detection. Currently we are working on creating object detection sample using Tiny_Yolo2 Onnx model available [here.](https://github.com/onnx/models/tree/master/tiny_yolov2).The documentation of this model can be found [here](http://machinethink.net/blog/object-detection-with-yolo/)

**Comment by davidlfox** [comment]
@prathyusha12345 will the object detection sample be standalone like many of the other examples?

**Comment by CESARDELATORRE** [comment]
Yes, Standalone. But notice that the sample will only be for scoring an ONNX model, not training the model, comparable to our TensorFlow samples but ‘Object Detection’ and ONNX model.

**Comment by prathyusha12345** [comment]
@davidlfox I have added object detection sample. Please find it in the link https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx

or you can go from the landing page(https://github.com/dotnet/machinelearning-samples) also as shown below.

![image](https://user-images.githubusercontent.com/22335043/55572883-857ed400-56bd-11e9-8745-a2274ff165e2.png)

**Comment by turowicz** [comment]
@prathyusha12345 is there a reason why it's using ONNX instead just TF model?

**Comment by CESARDELATORRE** [comment]
The main reason is that we also wanted to have an ONNX sample since we already have two TensorFlow samples already.

If you have any comparable model in TF feel free to submit a PR with similar code in ML.NET. :)

**Comment by turowicz** [comment]
I'll stay with TF#

**Comment by CESARDELATORRE** [comment]
Closing this issue since we already have an Object Detection sample.

**Comment by justinormont** [comment]
I think we could use a DnnImageFeaturizer example. This is rather better suited for the task anyhow, as its purpose in life is to make it very easy to run Object Detection. It sets up a pre-trained image model (AlexNet/Resnet) for you and output the correct layer. 

We also have nugets created which distributes the image models. The nugets have the gain of being easy for developers to include in their builds.

I would recommend using the DnnImageFeaturizer in examples instead of TensorFlow or ONNX when doing image classification.
