### ISSUE TITLE
How to transform Date column into C# DateTime Column?

### ISSUE THREAD

**Issue by agarwal-peeush** [dotnet/machinelearning-samples#336]
I'm working on a specific regression problem which provides Date of journey in string in dd/MM/yyyy format. How can I GetColumn as C# DateTime datatype column?

```
public class IssueSample
{
        [LoadColumn(0)]
        public string Col1;
        [LoadColumn(1)]
        public string DateOfJourneyStr;
        
        private const string DATETIME_FORMAT = "dd/MM/yyyy";
        public DateTime? DateOfJourney
            => ParseDateTime(DateOfJourneyStr);
        public static DateTime? ParseDateTime(string dateOfJourneyStr)
        {
            if (DateTime.TryParseExact(dateOfJourneyStr, DATETIME_FORMAT, CultureInfo.InvariantCulture, DateTimeStyles.None, out var result))
                return result;
            return null;
        }
}
```

I'm trying to get Min and Max DateOfJourney values as following:
```
private static void BuildTrainEvaluateAndSaveModel(MLContext mlContext)
        {
            // STEP 1: Common data loading configuration
            IDataView baseTrainingDataView = mlContext.Data.LoadFromTextFile<IssueSample>(TrainDataPath, hasHeader: true, separatorChar: ',');
            IDataView testDataView = mlContext.Data.LoadFromTextFile<IssueSample>(TestDataPath, hasHeader: true, separatorChar: ',');

            var dateOfJourneyMin = baseTrainingDataView.GetColumn<DateTime?>(mlContext, nameof(IssueSample.DateOfJourney)).Min();
            System.Console.WriteLine($"Min DateOfJourney = {dateOfJourneyMin}");
            var dateOfJourneyMax = baseTrainingDataView.GetColumn<DateTime?>(mlContext, nameof(IssueSample.DateOfJourney)).Max();
            System.Console.WriteLine($"Max DateOfJourney = {dateOfJourneyMax}");
        }
```

But I get an error as follows: 

> System.ArgumentOutOfRangeException: 'Could not find input column 'DateOfJourney'
> Parameter name: columnName'

Could somebody suggest how to achieve this in ML.NET?

**Comment by prathyusha12345** [comment]
I am not sure if we can do datatype conversions in the data class before loading the data into dataview. Can you post your issue in ML.Net repo [here](https://github.com/dotnet/machinelearning/issues) .

@CESARDELATORRE adding for reference

**Comment by eerhardt** [comment]
@agarwal-peeush - check out [How can I define my own transformation of data?](https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md#how-can-i-define-my-own-transformation-of-data) in our cookbook.  You can use one of these custom transforms to do the conversion from a string to a DateTime.

cc @TomFinley

**Comment by agarwal-peeush** [comment]
@prathyusha12345 Thanks for suggestion. I've now post this issue in ML.NET repo [here](https://github.com/dotnet/machinelearning/issues/3186).
@eerhardt I looked into link for cookbook, but still not convinced if I can use that. I'll have a look into the code and see if that works. Thanks for help.

Closing this issue here. Moved to ML.NET repo [here](https://github.com/dotnet/machinelearning/issues/3186).
