### ISSUE TITLE
The project does not support adding package references through the add package command.

### ISSUE THREAD

**Issue by AJain2810** [dotnet/machinelearning-samples#343]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install-package
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I created a new C# based Windows Form Application in Visual Studio 2019 Preview. After creating the application, I went to the folder and through an instance of CMD tried to install the ML.NET package in the folder directory. 
And I got an error message stating that the project does not support adding packages through the add package command. 

The version of .NET Framework used: 4.7 <something>
Version of .NET SDK: 2.1.602

**Comment by CESARDELATORRE** [comment]
Looks like this is not related to the ML.NET samples but this might be an issue either related to tooling or ML.NET itself.
Can you report it in the ML.NET repo issues instead?

https://github.com/dotnet/machinelearning/issues 

Thanks for reporting the issue! 👍

**Comment by CESARDELATORRE** [comment]
Closing the issue in the samples repo. Please, open that tooling/framework issue at the ML.NET repo issues instead:

https://github.com/dotnet/machinelearning/issues

Thanks for reporting the issue! 👍

**Comment by DarcyF-x** [comment]
I also encountered this problem in visual studio 2015. Create a console program. When adding a reference. I received an error message stating that the project does not support adding packages via the add package command. Is the method wrong or does not support ML.Net in 2015?

**Comment by StuckInsideJake** [comment]
I JUST WANT THIS TO FUCKING WORK!!!!!!!!!!!!!!!!!!!!!!!!!!!!
