### ISSUE TITLE
Regression-SalesForecast sample README file with link broken

### ISSUE THREAD

**Issue by dloperab** [dotnet/machinelearning-samples#344]
In the Regression sample for Sales Forecasting (https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Regression-SalesForecast), the link to show an explanation of the dataset:

![image](https://user-images.githubusercontent.com/16327575/55524909-84fe2300-5654-11e9-8692-9cacc3a4f14c.png)

Throws a 404:

![image](https://user-images.githubusercontent.com/16327575/55524946-a9f29600-5654-11e9-89e0-87f8171efaec.png)

**Comment by prathyusha12345** [comment]
@dloperab I fixed it. Thanks for reporting. Please check now. 

I am closing the issue. Please reopen if you encounter issue again. Thanks.
