### ISSUE TITLE
String to float conversion

### ISSUE THREAD

**Issue by PeterSoder** [dotnet/machinelearning-samples#345]
String to float conversion does not work in cultures with something other then period as decimal separator, maybe use CultureInfo.InvariantCulture explicitly.

https://github.com/dotnet/machinelearning-samples/blob/cb6ba8437bfc7175d2815a378510f88f115cecd7/samples/csharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction/TaxiFarePredictionConsoleApp/Program.cs#L317

**Comment by prathyusha12345** [comment]
As this issue is fixed, I am closing the issue.
