### ISSUE TITLE
Problem with ML.NET Tutorial - Get started in 10 minutes

### ISSUE THREAD

**Issue by jomardyan** [dotnet/machinelearning-samples#349]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/code
Operating System: windows

using Microsoft.Data.DataView;
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
//more  code.....
`
            // STEP 3: Transform your data and add a learner
            // Assign numeric values to text in the "Label" column, because only
            // numbers can be processed during model training.
            // Add a learning algorithm to the pipeline. e.g.(What type of iris is this?)
            // Convert the Label back into original text (after converting to number in step 3)
            var pipeline = mlContext.Transforms.Conversion.MapValueToKey("Label")
                .Append(mlContext.Transforms.Concatenate("Features", "SepalLength", "SepalWidth", "PetalLength", "PetalWidth"))
                .AppendCacheCheckpoint(mlContext)
                .Append(mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(labelColumnName: "Label", featureColumnName: "Features"))
                .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));`
//more  code.....

**Error CS1061**  'MulticlassClassificationCatalog.MulticlassClassificationTrainers' does not contain a definition for 'SdcaMaximumEntropy' and no accessible extension method 'SdcaMaximumEntropy' accepting a first argument of type 'MulticlassClassificationCatalog.MulticlassClassificationTrainers' could be found(are you missing a using directive or an assembly reference?)	AI Test C:\Users\Hayk\source\repos\AI Test\AI Test\Program.cs	61	Active

**Comment by prathyusha12345** [comment]
Are you using ML.Net **1.0.0-preview** nuget package? Either add like the following from the CLI or by using Visual Studio?:

`dotnet add package Microsoft.ML --version 1.0.0-preview`

Please let me know if you still encounter any issue.

**Comment by CESARDELATORRE** [comment]
The 'Getting Started' tutorial works good. Please, check it out when possible, ok?
See it running it on macOS (Also rund on Windows with no issues):

![image](https://user-images.githubusercontent.com/1712635/55677403-80777b80-589b-11e9-9d23-4ad6c4bf8c52.png)

Check this other issue. https://github.com/dotnet/machinelearning-samples/issues/347

Closing the issue for now. Feel free to re-open if you are still experiencing issues, ok?
