### ISSUE TITLE
MNIST Classification README.md is not completely altered from Iris

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/machinelearning-samples#355]
https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/MulticlassClassification_mnist/README.md

Find "iris"

**Comment by prathyusha12345** [comment]
@skyoxZ **MNIST classification** sample is different from **IRIS Classification** sample. But both samples are using same ML task i.e MultiClassClassification. 

Please let me know if you need more details.

**Comment by skyoxZ** [comment]
> @skyoxZ **MNIST classification** sample is different from **IRIS Classification** sample. But both samples are using same ML task i.e MultiClassClassification.
> 
> Please let me know if you need more details.

Sorry I did not make myself clear. 
I mean, we can still find (Ctrl+F) the word "iris" in MNIST README.md.

**Comment by prathyusha12345** [comment]
Ok. I got it. Thanks for identifying this. I have fixed it. Please check here https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/MulticlassClassification_mnist/README.md. 

I am closing the issue. thanks 👍
