### ISSUE TITLE
Breaking code documentation is missing breaking change 'DefaultColumnNames' is inaccessible due to its protection level"

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning-samples#358]
Hi,

I have updated to the latest preview to see what's coming and I noticed that all locations using 
DefaultColumnNames throws an error stating that it is no longer available due to its protection level. I did not find this mentioned in the docs/migrations/breaking-changes-1.0.0-preview.md

**Comment by CESARDELATORRE** [comment]
You're right. We'll update the breaking changes doc.
The team decided on making that class internal. See the PR here:
https://github.com/dotnet/machinelearning/pull/2842

If you have any comment/feedback about it, please do so in that PR, ok? 👍

**Comment by CESARDELATORRE** [comment]
Closing this issue for the reasons above.
