### ISSUE TITLE
Dead code in SpamDetectionConsoleApp

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-samples#361]
Code appears to not be used:
https://github.com/dotnet/machinelearning-samples/blob/75d5f3fd2776f5b603a370a69a4f3cc28bf2cde8/samples/csharp/getting-started/BinaryClassification_SpamDetection/SpamDetectionConsoleApp/Program.cs#L84-L92

**Comment by prathyusha12345** [comment]
@justinormont  Thanks for identifying. I have fixed this. Closing the issue.

Thanks 👍
