### ISSUE TITLE
build.ps1 is in error

### ISSUE THREAD

**Issue by tikrimi** [dotnet/machinelearning-samples#362]
The build.ps1 command gets all solution files, in order to apply the "dotnet build" command.
The issue is that inside solutions, thare are some project witch are not dotnet core projects (ShampooSalesSpikesWinForms as an example).

You can reproduce the issue by running this command:

dotnet build C:\Workspace\machinelearning-samples\samples\csharp\end-to-end-apps\SpikeDetection-ShampooSales-WinForms\ShampooSalesSpikeDetection.sln

So we ned to find a way to exclude this action from the build script, and build this solution in another way.

**Comment by prathyusha12345** [comment]
@tikrimi  Currently to run CI build successfully, I have added other solution file with just console App. Can you replace the above with  `dotnet build C:\Workspace\machinelearning-samples\samples\csharp\end-to-end-apps\SpikeDetection-ShampooSales-WinForms\ShampooSalesSpikeDetectionConsole.sln` for the build to succeed.

In future when .Net core 3 is released we migrate the sample and we will add the **ShampooSalesSpikeDetection.sln** to build file.

Please let me know if you still face any issue. ok? Thanks.

Adding @CESARDELATORRE  for reference.

**Comment by prathyusha12345** [comment]
Is your error resolved? Closing the issue. Please reopen if you encounter the issue.
