### ISSUE TITLE
'MulticlassClassificationCatalog.MulticlassClassificationTrainers' does not contain a definition for 'SdcaMaximumEntropy'

### ISSUE THREAD

**Issue by danucalovj** [dotnet/machinelearning-samples#386]
'MulticlassClassificationCatalog.MulticlassClassificationTrainers' does not contain a definition for 'SdcaMaximumEntropy' and no accessible extension method 'SdcaMaximumEntropy' accepting a first argument of type 'MulticlassClassificationCatalog.MulticlassClassificationTrainers' could be found (are you missing a using directive or an assembly reference?)	Iris Example

Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/code
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dxdinh** [comment]
I ran into the same issue but resolved by install the correct Microsoft.ML --version 1.0.0-preview

So remove the Microsoft.ML 
dotnet remove package Microsoft.ML
Then reinstall the package with version specified
dotnet add package Microsoft.ML --version 1.0.0-preview

![image](https://user-images.githubusercontent.com/5952219/56699722-95ca1380-66ab-11e9-94ff-8a1ba57af863.png)

Good luck !!!!

**Comment by prathyusha12345** [comment]
Have you tried the above steps?  I am closing the issue. Please reopen if you encounter the issue again

**Comment by danucalovj** [comment]
Thank you. Resolved.
