### ISSUE TITLE
Defining MLNetVersion for all projects to use

### ISSUE THREAD

**Issue by singlis** [dotnet/machinelearning-samples#388]
I noticed that the sample projects use MLNetVersion to determine the version of the ML.Net nuget package to use, however this looks to be defined in the DeepLearning_ObjectDetection_Onnx project:
https://github.com/dotnet/machinelearning-samples/blob/e78e227d0269accbc74db26a1edffd0b782d2511/samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/Directory.Build.props#L4

I am surprised this works (unless its really defined elsewhere). Should we move this to a more central props file that each project can reference?

**Comment by prathyusha12345** [comment]
Thanks for identifying. I removed this file from the project folder.

**Comment by prathyusha12345** [comment]
I am closing the issue. Feel free to reopen if you still encounter the same.

**Comment by singlis** [comment]
Thank you for clarifying @prathyusha12345, when I originally looked my local repo was out of date. Im good with closing the issue.
