### ISSUE TITLE
Problem with ML.NET Tutorial - Get started in 10 minutes

### ISSUE THREAD

**Issue by caloyboy** [dotnet/machinelearning-samples#392]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/run
Operating System: windows

The output I got was:
Predicted flower type is:
Press any key to exit....

I went through the tutorial step by step and prediction.PredictedLabels returned null.

**Comment by prathyusha12345** [comment]
I just did the steps by following the tutorial https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/run. I am receiving the output flower type as **Iris-virginica**

![image](https://user-images.githubusercontent.com/22335043/56914308-a215ee00-6a68-11e9-970b-9a054f90a870.png)


Can you please follow the tutorial steps one more time and let me know if you are still facing issue.

**Comment by prathyusha12345** [comment]
Is your issue resolved? I am closing the issue hoping its resolved. Please reopen the issue if you face any problem. Ok?
