### ISSUE TITLE
CommonHelpers.csproj has NU1105 Error

### ISSUE THREAD

**Issue by jacky126ppro** [dotnet/machinelearning-samples#393]
CommonHelpers.csproj Has NU1105 Error ,didn't compile sln

**Comment by prathyusha12345** [comment]
I tried rebuilding on my end and the solution builds successfully. 
![image](https://user-images.githubusercontent.com/22335043/56824787-52d38180-680c-11e9-9a4e-f9f0c7e49f66.png)

Could you please specify what the exact error is and details about the error you are facing?

**Comment by jacky126ppro** [comment]
Cannot be found CommonHelpers.csproj at compile eShopDashboardMLsln, Dependency warning,

Details:
"Project information for 'F:\machinelearning-samples-master\samples\csharp\end-to-end-apps\Regression-SalesForecast\src\CommonHelper\CommonHelpers.csproj' could not be found. In Visual Studio, this may be because the project has been uninstalled or is not part of the current solution. Otherwise, the project file may be invalid or lack the target required for the restore."

thanks

**Comment by jacky126ppro** [comment]
> Cannot be found CommonHelpers.csproj at compile eShopDashboardMLsln, Dependency warning,
> 
> Details:
> "Project information for 'F:\machinelearning-samples-master\samples\csharp\end-to-end-apps\Regression-SalesForecast\src\CommonHelper\CommonHelpers.csproj' could not be found. In Visual Studio, this may be because the project has been uninstalled or is not part of the current solution. Otherwise, the project file may be invalid or lack the target required for the restore."
> 
> thanks

add project conference
