### ISSUE TITLE
Web view not populating in Regression-SalesForecast

### ISSUE THREAD

**Issue by montebhoover** [dotnet/machinelearning-samples#397]
In [Regression-SalesForecast](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Regression-SalesForecast) the website does not seem to be working out of the box.  The web page serves, but doesn't get populated with info as shown in the readme.  Here's what it looked like when I ran it from the repo with no modifications:

![image](https://user-images.githubusercontent.com/37886197/56904025-1e7af200-6aa6-11e9-8c86-b3c56c914ed3.png)

Repro steps:
1. Clone dotnet/machinelearning-samples
2. Open eShopDashboardML.sln in Visual Studio 2019
3. Press F5 to run eShopDashboard project in Debug configuration
4. Web page displays , but no content is populated

**Comment by prathyusha12345** [comment]
You need to search for a product with say "bottle" in search box where **Type a product** tool tip string displays like below.
![image](https://user-images.githubusercontent.com/22335043/56922749-d1832580-6a7d-11e9-92e3-21f4d64c8dfa.png)

once you select any product from search drop down, and press Enter, it will show the product forecast results as shown below.

![image](https://user-images.githubusercontent.com/22335043/56922875-127b3a00-6a7e-11e9-8437-b140bda55911.png)

**Comment by prathyusha12345** [comment]
I fixed one build issue in master. Please take latest changes in your repo.

**Comment by montebhoover** [comment]
Thank you, this looks great.  Thanks for adding the FastTree reference into master.  The instruction to search for a product is exactly what I needed - if you don't mind I'll create a PR to add that to the instructions and you can decide if it is helpful.

Also, in one of the recent changes the CommonHelpers csproj was added, but it looks like it still needs to get added to the .sln to work out of the box.  I created #398 to make note of this.  Also, I created #399 to mention a few documentation suggestions in case you find them helpful.

Thanks for making this great sample!
