### ISSUE TITLE
Regression-SalesForecast no longer builds successfully.

### ISSUE THREAD

**Issue by montebhoover** [dotnet/machinelearning-samples#398]
[Regression-SalesForecast](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Regression-SalesForecast) no longer builds after cloning from master due to the refactoring in #391.  A new project "CommonHelpers" was added, but it looks like it doesn't build with projects that reference it.  If CommonHelpers.csproj is explicitly added to the .sln it will build properly.

**Comment by montebhoover** [comment]
By the way, the SalesForecast web app sample is really impressive.  Well done!

**Comment by prathyusha12345** [comment]
@montebhoover I fixed the issue and pushed into master. We need to add reference to commonHelpers.csproj in solution to fix the issue.Could you please take latest of master and try again.

**Comment by montebhoover** [comment]
Looks good, thanks!
