### ISSUE TITLE
Clarify a few things in Regression-SalesForecast documentation.

### ISSUE THREAD

**Issue by montebhoover** [dotnet/machinelearning-samples#399]
In #397 I had a problem with the web view because it wasn't apparent to me that I needed to enter a search term first in order to get the web page to populate.  Maybe adding a line stating so would help users like me - I'll let you decide.  Also, the first portion of the documentation deals with NuGet configuration but no action is necessary (only optional), so maybe it would help to get straight to the actionable steps and mention the NuGet configs as a footnote or something.  I'll create a PR with some suggested edits and feel free to take as much or as little as you find helpful.

**Comment by prathyusha12345** [comment]
Great!!! Thanks for coming up with suggestion.It would be better to add the info in ReadMe file. Let me add it and update.

**Comment by prathyusha12345** [comment]
I have added the info in ReadMe file in this commit https://github.com/dotnet/machinelearning-samples/commit/dbe1a9cad04b4285a8be8b2dd95f0bb35ed8e45a#diff-2fb36f80bcbc39cf9c2bff427bce6fa4. 

I am closing the issue. Feel free to reopen this issue if you still need any more info to be added.
