### ISSUE TITLE
Download link is not working

### ISSUE THREAD

**Issue by karthikperneti** [dotnet/machinelearning-samples#414]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by prathyusha12345** [comment]
link is fixed now. Could you please check.

**Comment by ElGranLuisR** [comment]
Still not working.

**Comment by prathyusha12345** [comment]
Can you try accessing the link https://marketplace.visualstudio.com/items?itemName=MLNET.07.

**Comment by SuperDaveOsbourne** [comment]
We're sorry, the page you requested cannot be found!

**Comment by rajach** [comment]
I still see the same issue

**Comment by prathyusha12345** [comment]
The issue is fixed now. Can you try accessing the link now .

**Comment by rustd** [comment]
Please re-open this if the issue still happens.
