### ISSUE TITLE
Terminal command doesn't match explanation

### ISSUE THREAD

**Issue by sitwalkstand** [dotnet/machinelearning-samples#422]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/train#
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The Terminal command has the parameter "--has-header false", but the example data and the explanation later in the page indicates that the parameter should be "--has-header true".

**Comment by briacht** [comment]
This has been fixed: https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/train

**Comment by prathyusha12345** [comment]
@sitwalkstand  can you try the steps again following the tutorial and let me know if you face the issue again

**Comment by sitwalkstand** [comment]
I just ran through the steps again and the tutorial works as intended.  Thank you!
