### ISSUE TITLE
Documentation mentions inception v3 but inception5h (v1) is used

### ISSUE THREAD

**Issue by tarnow74** [dotnet/machinelearning-samples#423]
I am having trouble using my own retrained inception v3 model with this example. Inspecting the tensorflow graph it seems to me like this example is using inception5h and not v3. The v3 model has no 'input' / 'softmax2' tensors but has 'DecodeJPeg' / 'final_result' tensors.

**Comment by prathyusha12345** [comment]
Could you let me know which sample are you discussing about in our Machine Learning samples repo?

**Comment by CESARDELATORRE** [comment]
You are right, in the samples we're using inception5h and not v3. Can you point to the documentation where it is saying it is using Inception v3?

Thanks for raising this up! 👍

**Comment by prathyusha12345** [comment]
Fixed this in this commit https://github.com/dotnet/machinelearning-samples/commit/64cf1c1d45ccb783ec149e0c1c9049d7432646ab#diff-cbac7c6bbf7cfce04fa46eb931243f2a. Thanks  👍
