### ISSUE TITLE
get start with error

### ISSUE THREAD

**Issue by bh1rio** [dotnet/machinelearning-samples#425]
walk throught the get start guide, but there are some errors......

[debug_log.txt](https://github.com/dotnet/machinelearning-samples/files/3155309/debug_log.txt)

**Comment by danucalovj** [comment]
Can you post a sample of your data? What format is it in?

**Comment by prathyusha12345** [comment]
At which step you are receiving this error? on **Download and install** step https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install? Which O.S you are using?

**Comment by prathyusha12345** [comment]
Are you able to access this link https://marketplace.visualstudio.com/items?itemName=MLNET.07? have you installed vsix template from the link?

**Comment by bh1rio** [comment]
the step : Train your model.
I run it with cli
```
mlnet auto-train --task binary-classification --dataset "wikipedia-detox-250-line-data.tsv" --label-column-name "Sentiment" --max-exploration-time 10
```

**Comment by danucalovj** [comment]
@bh1rio could you specify a few more details, such as full directory you're trying to run the command on, verifying the .tsv file is in the same directory you're running the mlnet command, whether that directory is a user directory (Desktop, Documents, etc.) or at a different non-user directory where permissions may be an issue, i.e.: root of C:\, and whether you're using a regular user level command prompt or an elevated session?

Also, can you try opening the tsv file to make sure everything looks ok?

I tried to replicate the issue on my system, I can't replicate it on my end:

![image](https://user-images.githubusercontent.com/12853868/57424575-f5a4dc00-71cc-11e9-99d0-669415e6871c.png)

When you installed mlnet via **dotnet tool install -g mlnet**, was it as an elevated administrator command prompt (Run As > Administator)? Or did you install it as your regular user account?

**Comment by bh1rio** [comment]
no error with run as administrator.

 :flushed:

**Comment by danucalovj** [comment]
Awesome :)

**Comment by bh1rio** [comment]
I install a new clear os for test, and there is none error with only dotnet core sdk 2.2.203.
So I guess the error by dotnet core sdk 3.0-preview5

**Comment by CESARDELATORRE** [comment]
@bh1rio Can you specify what error are you getting and what versions of operating system?

**Comment by bh1rio** [comment]
> 
> 
> @bh1rio Can you specify what error are you getting and what versions of operating system?

error log on the top

**Comment by justinormont** [comment]
@bh1rio: In your debug_log.txt, the error is listed as `System.InvalidOperationException: Could not parse value Sentiment in line 1, column Label`.

This is saying it found "Sentiment" in your 1st row of the dataset. This is likely a header row. Can you set `--has-header true` in the CLI?

**Comment by bh1rio** [comment]
i can't redo the sample.
the sample data be updated one day ago.

now there is none error

**Comment by CESARDELATORRE** [comment]
Closing the issue since it looks like there's no error now.
Thanks! 👍
