### ISSUE TITLE
unable to install ML.NET NuGet package

### ISSUE THREAD

**Issue by CarloDonatiAreteMethodos** [dotnet/machinelearning-samples#427]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/consume
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by danucalovj** [comment]
Also, see this:

https://github.com/NuGet/Home/issues/6430

**Comment by danucalovj** [comment]
Have you tried the same on a folder in your user directory and get the same issue?

**Comment by prathyusha12345** [comment]
@CarloDonatiAreteMethodos You can install the ML.NET CLI tool directly by following the steps in command prompt as given in the link https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install

**Comment by prathyusha12345** [comment]
@CarloDonatiAreteMethodos have you tried the steps again? I am closing the issue. Please reopen if you face the issue again. Ok? 

Thanks.
