### ISSUE TITLE
Error Installing Extension

### ISSUE THREAD

**Issue by satbirbaidwan** [dotnet/machinelearning-samples#429]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows 10

Extension is not installing
Error log says: 
The extension with ID 'FE96D051-645F-4309-AE99-107A776B0DA2' is not installed to Microsoft SQL Server Data Tools for Visual Studio 2017 (SSDT)

5/8/2019 4:13:12 PM - Extension cannot be installed to the following products due to missing prerequisites:
5/8/2019 4:13:12 PM - 	Microsoft SQL Server Data Tools for Visual Studio 2017 (SSDT)
5/8/2019 4:13:12 PM - 		-------------------------------------------------------
5/8/2019 4:13:12 PM - 		Identifier   : Microsoft.VisualStudio.Workload.NetCoreTools
5/8/2019 4:13:12 PM - 		Name         : .NET Core cross-platform development
5/8/2019 4:13:12 PM - 		Version      : [15.0,17.0)
5/8/2019 4:13:12 PM - 		Error        : The prerequisite specified does not exist
5/8/2019 4:13:12 PM - 
5/8/2019 4:13:12 PM - 		-------------------------------------------------------
5/8/2019 4:13:12 PM - 		Identifier   : Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1
5/8/2019 4:13:12 PM - 		Name         : .NET Core 2.1 development tools
5/8/2019 4:13:12 PM - 		Version      : [15.0,17.0)
5/8/2019 4:13:12 PM - 		Error        : The prerequisite specified does not exist

I have SSDT tools installed
and .Net Core Cross-platform development Toolsets installed

**Comment by JakeRadMSFT** [comment]
Microsoft SQL Server Data Tools for Visual Studio 2017 is not a supported version of Visual Studio.

Please use a standard Visual Studio 2017 (Community, Pro, Enterprise) or Visual Studio 2019(Community, Pro, Enterprise)

Please refer to:https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017 for more details on the differences between SSDT and standard installs.

Thanks for reporting!

**Comment by JakeRadMSFT** [comment]
Closing issue, but please open the issue if you have any more questions.

**Comment by rustd** [comment]
I have updated the doc (https://aka.ms/modelbuilderdocs) as well to reflect this as well
