### ISSUE TITLE
Error in installation of Model builder

### ISSUE THREAD

**Issue by santoshdwive** [dotnet/machinelearning-samples#431]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows
![image](https://user-images.githubusercontent.com/39820111/57428152-adc19b80-7244-11e9-990b-88f2ebc5b9d8.png)

Please see the path error in attached image.

**Comment by JakeRadMSFT** [comment]
Does visual studio run successfully? I've only seen this issue when there is a problem installing Visual Studio. 

Do you see any issues if you open up Visual Studio Installer?

**Comment by CESARDELATORRE** [comment]
Closing this issue. We added it to the ML.NET repo.
Please add tooling or framework issues to the ML.NET Repo.
Issues here should be related to the ML.NET Samples.
Thanks for the feedback! :)

**Comment by CESARDELATORRE** [comment]
Closing this issue. We added it to the ML.NET repo.
Please add tooling or framework issues to the ML.NET Repo.
Issues here should be related to the ML.NET Samples.
Thanks for the feedback! :)
