### ISSUE TITLE
Install button is disabled.

### ISSUE THREAD

**Issue by shishir84** [dotnet/machinelearning-samples#433]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by prathyusha12345** [comment]
Are you able to access the link https://marketplace.visualstudio.com/items?itemName=MLNET.07 and is it showing **download** button as below?

![image](https://user-images.githubusercontent.com/22335043/57474375-ce8af080-7246-11e9-8c83-6c90c26c360c.png)

**Comment by rustd** [comment]
Closing this issue. Please open a new issue if you are still having issues downloading Model Builder.
