### ISSUE TITLE
Unable to find package Microsoft.ML.

### ISSUE THREAD

**Issue by bblock84** [dotnet/machinelearning-samples#436]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/generate-code
Operating System: windows
VS2017 version 15.9.11
Using x64 as the platform

I cannot run the example as I receive the errors in the screenshot below:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package Microsoft.ML. No packages exist with this id in source(s): DTI, Microsoft Visual Studio Offline Packages, PackageSource	myMLAppML.Model	C:\Users\bblock\source\repos\ConsoleApp1\myMLAppML.Model\myMLAppML.Model.csproj	1	

![image](https://user-images.githubusercontent.com/50457076/57467216-bcf61880-7247-11e9-8154-4583f96f3469.png)

**Comment by hangy** [comment]
Can you check if the official NuGet.org feed is active in Visual Studio or in your solution's `NuGet.config` file? The package should be available [on there](https://www.nuget.org/packages/Microsoft.ML/).

**Comment by bblock84** [comment]
Pardon my ignorance, but I don't see a NuGet.config file anywhere in my solution folder.  I did see that the NuGet Package sources where not correctly set up in the NuGet Options screen.  I added a source for https://api.nuget.org/v3/index.json and everything compiled fine.

Thanks again for your help!
