### ISSUE TITLE
Evaluate Option is not available

### ISSUE THREAD

**Issue by nossareh** [dotnet/machinelearning-samples#438]
The Evaluate and Code option are not available. I am using VS 2017 - community edition. 

Is this by design or err?

Thanks
Nasser

**Comment by rustd** [comment]
Can you please add a screenshot and the scenario? Evaluate and Code will not be enabled if the Training process didn't generate a model. Read more https://aka.ms/modelbuilderdocs

**Comment by nossareh** [comment]
Thanks for the reply, The training completed successfully. I expected the next step "3 - Evaluate" to become available. It apparently takes a few minutes for processing, then it becomes enabled. I must have not been patient enough. 

So I am good for now.
Thanks

**Comment by asthana86** [comment]
Thanks for trying out Model Builder and provide this feedback 👍 

There is a slight issue here from a UX perspective that even after time is complete the finalizing model stage is not instant. 

We will try to address this in an upcoming release.
