### ISSUE TITLE
TensorFlow demo does not compile

### ISSUE THREAD

**Issue by arafattehsin** [dotnet/machinelearning-samples#44]
Hi Team

TensorFlow demo does not compile properly because it requires ML.NET 0.6 Preview version which is not available in NuGet (even if I select 'Include Prelease' option) 

Please have a look at it.

Thanks

**Comment by CESARDELATORRE** [comment]
You need to use the MyGet Nuget feed so you get 0.6
v0.6 is still Preview therefore is not in Nuget.
v0.5 has some issues and won’t work properly for that sample.

**Comment by arafattehsin** [comment]
I'm able to compile it with dotnet MyGet feed. 

Thanks Cesar!
