### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by NoofSaeidh** [dotnet/machinelearning-samples#45]
Broken image at page:
 https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/README.md
in Solution paragraph
current link:
https://github.com/dotnet/machinelearning-samples/raw/master/samples/getting-started/shared_content/modelpipeline.png

**Comment by NoofSaeidh** [comment]
For others readmes in others examples, the same problem.
Seems like the link should be the following: https://raw.githubusercontent.com/dotnet/machinelearning-samples/master/samples/csharp/getting-started/shared_content/modelpipeline.png

**Comment by divyanshkul** [comment]
Can I work on this?

**Comment by justinormont** [comment]
Closed by #47, #48, #49, & #54

@divyanshkul : Sure, as always just submit a pull request
