### ISSUE TITLE
Proper Orientation

### ISSUE THREAD

**Issue by dev-variety** [dotnet/machinelearning-samples#455]
Is this possible with ML.NET?

**Comment by CESARDELATORRE** [comment]
@dev-variety - Sorry, can you be more specific on the question? 
Can you provide further details about your question on "Proper Orientation"?

**Comment by dev-variety** [comment]
I'm seeking if RotNet could be possible with ML.NET

**Comment by CESARDELATORRE** [comment]
I don't think so. If you mean this: https://github.com/d4nst/RotNet

ML.NET is custom machine learning for traditional ML tasks based on data such as:
- Classification
- Regression
- Clustering
- Recommendations
- Anomaly Detection

With Rotnet if you mean any specific problem (image orientation) using 'convolutional neural networks (CNNs)', for that you'd need any deep learning framework such as TensorFlow/KEras.

However, once you have the trained TF model, ML.NET can run/score TensorFlow models or even do transfer learning, but not TensorFlow training, only scoring/running that model.

**Comment by CESARDELATORRE** [comment]
Closing the issue. Open it again if needed.

**Comment by dev-variety** [comment]
I was using the image classification sample, but it was not good as expected. I am using the the estimator sample now, and tuned it up a bit and it's working somewhat better than the other sample.

Thank you!
