### ISSUE TITLE
I have just installed ML.Net on VS2019. The wiki training file is downloaded and parsed correctly into the preview window. When clicking the Start Training button no training occurs. The Machine Learning Output windows shows "'Test' was not recognised. Did you mean 'T', or '-t'?" and no Progress data is shown. The Evaluate is empty and no code is generated in the subsequent steps.

### ISSUE THREAD

**Issue by groblerf** [dotnet/machinelearning-samples#456]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/train
Operating System: windows
VS 2019 (16.0.4)
Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by groblerf** [comment]
![image](https://user-images.githubusercontent.com/10207921/57761536-02aa5980-76fe-11e9-9eb2-7aaa92dd6a6a.png)

**Comment by rustd** [comment]
Thank you for reporting this issue. /cc @JakeRadMSFT @tbombach

**Comment by tbombach** [comment]
Hi @groblerf, thank you for bringing this issue to our attention! Is there a space in the name of your solution (like "Test App")? We currently have an issue where we don't handle spaces in the solution name very well. We will fix this in our next release, but for now you can use the following steps to successfully train a model:

1) Right click on your solution (not the project) and rename it without a space
2) Close the "ML.NET Model Builder" window
3) Re-open Model Builder via `Add->Machine Learning`
4) Follow the tutorial steps again

My sincerest apologies for this issue. We'll be sure to fix this in our next release.

**Comment by groblerf** [comment]
Thanks Thomas! Removing the spaces from the Solution and Project Names worked.
I look forward to the next release. Keep up the good work.
