### ISSUE TITLE
Training failed (PosSample) parameter with custom tsv training dataset

### ISSUE THREAD

**Issue by cdslijngard** [dotnet/machinelearning-samples#460]
Hi,
I can't create a model based on the following training dataset. I am just playing around trying to create a model which determines positive and negative numbers.

Dataset is included. (I changed it to TXT to include is in this post.)
[negativepositivenumbers.txt](https://github.com/dotnet/machinelearning-samples/files/3186518/negativepositivenumbers.txt)

I tried the values with and without quotes. Am I doing something wrong or should this work?

**Comment by CESARDELATORRE** [comment]
Can you provide the error you are getting?
Also the training pipeline C# code?

Btw, I know you know this but for determining if a number is positive or negative.., that problem can be solved in a much more effective way with simple code like the following:

```
bool positive = number > 0;
bool negative = number < 0;
```

For machine learning problems, try to find problems that are really hard to solve with math or traditional algorithms and need to be solved by training a model with many samples (usually thousands of samples in the dataset, if not millions of samples for good quality models).

**Comment by prathyusha12345** [comment]
Closing this issue. Please provide more details like what scenario you are doing,what ML Task you are using like Binary Classification, Multi class Classification etc.Are you following any sample in our samples repo to do this task? Please reopen if you encounter any issue again, OK? Thanks 👍
