### ISSUE TITLE
Neutral sentiment? 

### ISSUE THREAD

**Issue by abpatel** [dotnet/machinelearning-samples#464]
Is there support for neutral sentiments?
Often times a review / feedback doesn't necessarily qualify as positive or negative. 
Is there a way to designate a sentiment as neutral in training the model?

**Comment by CESARDELATORRE** [comment]
Sure, you could do that as well.
You just need a dataset with rows/comments/text labeled/marked as the following in the 'Label' column:

- Positive
- Neutral
- Negative

Than use a multi-class classification trainer instead of a binary classification trainer.

**Comment by abpatel** [comment]
Is there any guidance or samples on how to go about this and which multi clasd classification is appropriate? Also is this something that can be done using the model builder UI or would it have to be coded by hand ?

**Comment by CESARDELATORRE** [comment]
Multi-class classification is supported by VS Model Builder and also by the ML.NET CLI, so you'd just need that kind of dataset, then you can even have the code generated for you.

About samples, the GitHub issues classification sample we have in this repo could be a comparable sample (multi-class classification). You could implement something similar.

But the easiest way to do it would be to:
- 1. Create such a dataset
- 2. Use VS Model Builder or ML.NET CLI to train the "best model" and generate the code for you

Hope it helps. 👍 
Closing the issue for now.
