### ISSUE TITLE
Unsupported file type when loading dataset

### ISSUE THREAD

**Issue by slavenmisak** [dotnet/machinelearning-samples#465]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/data
Operating System: windows

It says "Unsupported file type" when trying to load the TSV file? 

Environment: Visual Studio 2017 15.9.12

![image](https://user-images.githubusercontent.com/2753473/57982671-ca31b500-7a48-11e9-8d4f-10819b9bc26f.png)

**Comment by CESARDELATORRE** [comment]
Can you provide/attach the exact dataset file you are trying to use?
Does the file you are trying to load the .tsv extension?

**Comment by samgill172** [comment]
I had the same problem and I had a .tsv.txt as an extension

**Comment by rustd** [comment]
Thank you for reporting this issue. We are looking at making this experience better in the future release. Please follow this bug https://github.com/dotnet/machinelearning-modelbuilder/issues/73 for further progress on this issue.
