### ISSUE TITLE
Predict label with Image Classification

### ISSUE THREAD

**Issue by developervariety** [dotnet/machinelearning-samples#466]
I have viewed some examples like @CESARDELATORRE ASP.NET Web API, but it's not updated to the latest which is something my project needs.

I'm trying to predict the label of the images with Image Classification. I have created my own model from tips from @CESARDELATORRE on other issues (using Azure).

The current example project has the label already, there should be an example to PREDICT the label unless I missed it.

**Comment by glebuk** [comment]
This should be similar to any other prediction example, such as one on the home page.  The only difference is that the image you are trying to predict has to be on disk and the input is file name.  We are working to fix it to allow in-memory images in next releases.

**Comment by developervariety** [comment]
Thank you @glebuk.

I will close this issue.
