### ISSUE TITLE
Error Installing Model Builder

### ISSUE THREAD

**Issue by hamlinstephen** [dotnet/machinelearning-samples#469]
Problem encountered on installing Model Builder
Operating System: windows
VS : 2017 Enterprise 15.7.1

Error : The extension cannot be installed to this product due to prerequisites that cannot be resolved.

**Comment by rustd** [comment]
Hi @hamlinstephen Please follow this bug for progress on this issue. https://github.com/dotnet/machinelearning-modelbuilder/issues/37
