### ISSUE TITLE
mlnet broken link

### ISSUE THREAD

**Issue by kumpera** [dotnet/machinelearning-samples#473]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/evaluate
Operating System: macos

The link https://aka.ms/mlnet-cli is broken.

**Comment by CESARDELATORRE** [comment]
I just fixed the AKA.MS url.
It should work now, closing the issue.

Thanks for the heads-up! 👍
