### ISSUE TITLE
no machine leaning

### ISSUE THREAD

**Issue by lc673850771** [dotnet/machinelearning-samples#474]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by prathyusha12345** [comment]
Could you please specify the details of the error you are facing

**Comment by CESARDELATORRE** [comment]
Closing this issue for now since we didn't get further details.
Re-open with additional repro info if needed.

Thanks,
