### ISSUE TITLE
Tensorflow samples for multiclass

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning-samples#479]
Would be nice to get some samples on  TensorFlow other than the one we have with image recognitions

**Comment by prathyusha12345** [comment]
we are going to add samples using Tensor flow that are not supported by ML.Net for model training like Object detection. For Multiclass we have set of below trainers. Please refer to this ML.Net.API link https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/tasks for supported tasks by ML.Net

LightGbmMulticlassTrainer
SdcaMaximumEntropyMulticlassTrainer
SdcaNonCalibratedMulticlassTrainer
LbfgsMaximumEntropyMulticlassTrainer
NaiveBayesMulticlassTrainer
OneVersusAllTrainer
PairwiseCouplingTrainer


Adding @CESARDELATORRE  for reference

**Comment by PeterPann23** [comment]
I know that these are available, I also know that TF is quite popular and being able to demonstrate the use of TF  of price prediction and multi-class [as shown in this Iris sample](https://www.kaggle.com/pierrek20/multiclass-iris-prediction-with-tensorflow-keras) is something that will be interesting to a large audience

**Comment by CESARDELATORRE** [comment]
I know there are many TensorFlow scenarios that might be interesting for folks, but our time bandwidth is very limited so we need to prioritize TensorFlow scenarios/samples that are NOT supported by ML.NET itself, such as anything related to images. But multi-class classification, regression, etc. are ML Tasks supported by ML.NET trainers and API.

However, if you create any of those TF samples/scenarios and create a PR with it, we'll be happy to review it and merge it as a TF sample for this repo which happily accepts open source contributions. :)

For now, I'm closing this issue, ok? Feel free to re-open if you think you need to.
Thanks for your feedback! 👍

**Comment by PeterPann23** [comment]
Yes, it is possible to execute Multi-Class using the API, the issue is that the quality of the network is rather bad and I have not found a way to get it near to production levels. Not sure why  I must be doing something wrong in the API or the Api developing against test data sets and not against production data.
