### ISSUE TITLE
Negative Scores on Matrix Factorization

### ISSUE THREAD

**Issue by diegoazevedo** [dotnet/machinelearning-samples#481]
I've been using the Product Recommentation sample available on https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MatrixFactorization_ProductRecommendation.

I did a couple of tests and I've found out that the Score property values is negative sometimes. I've thought that should be ranging from 0 to 1.

I did'nt find a documentation that explains what I should expect from that return.

**Comment by shmoradims** [comment]
We've added more information about inputs/outputs [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.matrixfactorizationtrainer?view=ml-dotnet-preview#input-and-output-columns). In general, ML.NET `Score` outputs are unbounded values and don't have a fixed range.

@wschin, please comment if MatrixFactorization `Score`  needs extra clarification.

**Comment by wschin** [comment]
The score produced by matrix factorization represents the likelihood of being a positive case. The larger the score value, the higher probability of being a positive case. However, the score doesn't carry any probability information. When making a prediction, you will have to compute multiple merchandises' scores and pick up the merchandise with the highest score.

**Comment by prathyusha12345** [comment]
Closing the issue. Please reopen if you have got any questions. Thanks 👍

**Comment by mentorfloat** [comment]
@wschin I trained a model with One Class Matrix Factorization to determine if Class A is better than Class B.
After making thousands of predictions, I noticed that the scores are _very_ close to one another. Some examples below. 

I understand that the scores are unbounded, but just want to make sure that this behavior is indeed normal and I can just rank them accordingly? Thanks

```
Class A | Class B | Score
157 | 145 | 1.009949
92 | 133 | 1.0084165
121 | 17 | 1.0091498
236 | 147 | 1.0098939
92 | 17 | 1.0087594
17 | 92 | 1.0088547
121 | 147 | 1.0098875
25 | 777 | 1.00861
121 | 360 | 1.0097605
236 | 360 | 1.0097562
360 | 92 | 1.0091851
121 | 133 | 1.0100565
360 | 236 | 1.0100011
121 | 133 | 1.0100565
360 | 236 | 1.0100011
236 | 360 | 1.0097562
245 | 163 | 1.0099963
163 | 164 | 1.010098
202 | 143 | 1.0094845
421 | 202 | 1.0097957
```

**Comment by acrigney** [comment]
So can we assume anything about the sign of the Score?
Can you make it so that the score only goes from 0-1?
I have values that can be less than -1 and it looks like I can read that as a positive identification with my data.
