### ISSUE TITLE
Error occurred during training

### ISSUE THREAD

**Issue by kelvinlau2005** [dotnet/machinelearning-samples#484]
Exception occured while exploring pipelines:
Provided label column 'Sentiment' was of type Boolean, but only type Single is allowed.
System.ArgumentException: Provided label column 'Sentiment' was of type Boolean, but only type Single is allowed.
   at Microsoft.ML.CLI.CodeGenerator.CodeGenerationHelper.GenerateCode()
   at Microsoft.ML.CLI.Program.<>c__DisplayClass1_0.<Main>b__0(NewCommandSettings options)
Please see the log file for more info.
Exiting ..

**Comment by CESARDELATORRE** [comment]
Can you provide the specific dataset and pipeline code you are trying?

**Comment by prathyusha12345** [comment]
Closing this issue. Please provide details if you encounter any issue again. Thanks 👍

**Comment by tmorford** [comment]
I am having this issue also.. 

0	Ins	2012	1	15	14	1	0	2
1	Ins	2015	2	121	13	2	1	1
0	Ins	2012	1	15	14	1	0	2
1	Ins	2015	2	121	13	2	1	1
0	Ins	2012	1	15	14	1	0	2
1	Ins	2015	2	121	13	2	1	1
0	Ins	2012	1	15	14	1	0	2
0	Ins	2015	2	121	13	2	1	1
1	Ins	2015	1 	92	13	2	1	1
0	Aft	2012	1	15	14	1	0	2

**Comment by CESARDELATORRE** [comment]
@tmorford - In what sample are you having that issue?
What ML task and algorithm are you using?

The SentimentAnalysis is using bool as the type for the label in the data-class with no issues:

```
public class SentimentIssue
{
    [LoadColumn(0)]
    public bool Label { get; set; }
    [LoadColumn(2)]
    public string Text { get; set; }
}
```
Here's the execution with no problems:

![image](https://user-images.githubusercontent.com/1712635/67055434-f5562880-f0fc-11e9-913a-e7f3eccf5689.png)

**Comment by luisquintanilla** [comment]
Closing this issue since a response was provided / error couldn't be reproduced and no further activity has occurred.
