### ISSUE TITLE
AUC is not definied when there is no positive class in the data

### ISSUE THREAD

**Issue by syune-ghazaryan** [dotnet/machinelearning-samples#492]
AUC is not definied when there is no positive class in the data
Parameter name: PosSample

**Comment by prathyusha12345** [comment]
Could you please provide the details of sample in which you are facing this issue.

**Comment by prathyusha12345** [comment]
Generally, to compute AUC, we need at least one positive and one negative labels. Does your data to evaluate contain negative labels? It's possible that your  data is too small so that AUC is not a well-defined metric.


Closing this  issue as more details are not available on this issue. Thanks :)
