### ISSUE TITLE
Zero metrics for all algorithms, but no error reported

### ISSUE THREAD

**Issue by natke** [dotnet/machinelearning-samples#496]
I ran Model Builder on the attached dataset targeting the multiclass classification task.

All metrics for all algorithms are 0.

I tried running for 100 seconds and 1000 seconds with the same result.

I tried .csv and .tsv format

[scenarios.xlsx](https://github.com/dotnet/machinelearning-samples/files/3242902/scenarios.xlsx)

The log file from Model Builder is also attached
[debug_log.txt](https://github.com/dotnet/machinelearning-samples/files/3242907/debug_log.txt)

(I created a pipeline manually in ML.NET:

     var pipeline = mlContext.Transforms.Conversion.MapValueToKey("Label", "Task")
        .Append(mlContext.Transforms.Text.FeaturizeText("Scenario_Features", "Scenario"))
        .Append(mlContext.Transforms.Concatenate("Features", "Scenario_Features"))
        .AppendCacheCheckpoint(mlContext)
        .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(mlContext.BinaryClassification.Trainers.AveragedPerceptron()) 
        .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedTask", "PredictedLabel")));

and that gave micro/macro accuracy of 0.75/0.83 with a few seconds of training)

**Comment by natke** [comment]
Wrong repo. Moved to Model Builder issue repo

**Comment by justinormont** [comment]
Reopened at https://github.com/dotnet/machinelearning-modelbuilder/issues/69
