### ISSUE TITLE
MultiLabels for Multi-Classification issue

### ISSUE THREAD

**Issue by arcontechnologies** [dotnet/machinelearning-samples#506]
Dear All,

I saw lot of posted issues regarding Multilabels Classification (predict several labels) but no one is giving how to concretly do that.

Can someone advice ?

Thanks in advance

**Comment by prathyusha12345** [comment]
Have you referred to IRIS Classification sample for mapping scores with labels https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MulticlassClassification_Iris? You get scores based on order of labels given in the dataset.

Let me know if you still need more details.

**Comment by prathyusha12345** [comment]
Closing the issue. Let me know if you still need any help, ok? Thanks
