### ISSUE TITLE
Large data set sample (evaluate model) documentation is wrong

### ISSUE THREAD

**Issue by nunocenteno** [dotnet/machinelearning-samples#512]
The sample for large data sets has a wrong description in the "Evaluate model" (https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/LargeDatasets#3-evaluate-model), because the description is related to another sample (the Wikipedia Detox) instead of the current sample case.

**Comment by prathyusha12345** [comment]
Thanks for identifying. I fixed it. Thanks
