### ISSUE TITLE
after downloading the wikipedia-detox-250-line-data.tsv it is showing error "Unsupported file type" on adding data

### ISSUE THREAD

**Issue by hariharan18** [dotnet/machinelearning-samples#513]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/data
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rustd** [comment]
Transferring this issue to the Model Builder repo. Please use this issue for any further updates https://github.com/dotnet/machinelearning-modelbuilder/issues/102
