### ISSUE TITLE
Error while training the Tutorial ML Model

### ISSUE THREAD

**Issue by vu3maz** [dotnet/machinelearning-samples#514]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/train
Operating System: windows

My operating system version: Win 10 Enterprise V1709, Build: 16299.1146

"Exception occured while exploring pipelines:
Provided label column 'SentimentText' was of type String, but only type Single is allowed.
System.ArgumentException: Provided label column 'SentimentText' was of type String, but only type Single is allowed.
   at Microsoft.ML.CLI.Program.<>c__DisplayClass1_0.<Main>b__0(NewCommandSettings options)
   at Microsoft.ML.CLI.CodeGenerator.CodeGenerationHelper.GenerateCode()

**Comment by CESARDELATORRE** [comment]
@vu3maz - I believe you specified the column 'SentimentText' as the label/target column to predict.
However, as specified in the tutorial, the column you should use as label/target is the column named 'Sentiment' which is Boolean/numeric (Single).

Please, select the 'Sentiment' column as label.

**Comment by prathyusha12345** [comment]
@vu3maz Have you tried the above solution? I am closing the issue. Please reopen if you still encounter issue after trying the above solution. Ok? Thanks :)
