### ISSUE TITLE
Running an issue in installation in Visual Studio Enterprise 2017 Version 15.6.5

### ISSUE THREAD

**Issue by sundersham** [dotnet/machinelearning-samples#521]
6/14/2019 12:53:45 PM - Microsoft VSIX Installer
6/14/2019 12:53:45 PM - -------------------------------------------
6/14/2019 12:53:45 PM - vsixinstaller.exe version:
6/14/2019 12:53:45 PM - 15.6.152+ge95e4dd1ce
6/14/2019 12:53:45 PM - -------------------------------------------
6/14/2019 12:53:45 PM - Command line parameters:
6/14/2019 12:53:45 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Softwares\MLNET_Model_Builder.vsix
6/14/2019 12:53:45 PM - -------------------------------------------
6/14/2019 12:53:45 PM - Microsoft VSIX Installer
6/14/2019 12:53:45 PM - -------------------------------------------
6/14/2019 12:53:56 PM - Initializing Install...
6/14/2019 12:53:56 PM - Extension Details...
6/14/2019 12:53:56 PM - 	Identifier         : FE96D051-645F-4309-AE99-107A776B0DA2
6/14/2019 12:53:56 PM - 	Name               : ML.NET Model Builder (Preview)
6/14/2019 12:53:56 PM - 	Author             : Microsoft
6/14/2019 12:53:56 PM - 	Version            : 16.0.1906.701
6/14/2019 12:53:56 PM - 	Description        : Simple UI tool to build custom machine learning models.
6/14/2019 12:53:56 PM - 	Locale             : en-US
6/14/2019 12:53:56 PM - 	MoreInfoURL        : 
6/14/2019 12:53:56 PM - 	InstalledByMSI     : False
6/14/2019 12:53:56 PM - 	SupportedFrameworkVersionRange : [4.5,)
6/14/2019 12:53:56 PM - 
6/14/2019 12:54:04 PM - 	SignatureState     : ValidSignature
6/14/2019 12:54:04 PM - 	SignedBy           : Microsoft Corporation
6/14/2019 12:54:04 PM - 	Certificate Info   : 
6/14/2019 12:54:04 PM - 		-------------------------------------------------------
6/14/2019 12:54:04 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
6/14/2019 12:54:04 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
6/14/2019 12:54:04 PM - 		[Serial Number] : 330000026ECE6AE5984BFC96A900000000026E
6/14/2019 12:54:04 PM - 		[Not Before]    : 9/7/2018 2:30:30 AM
6/14/2019 12:54:04 PM - 		[Not After]     : 9/7/2019 2:30:30 AM
6/14/2019 12:54:04 PM - 		[Thumbprint]    : 99B6246883B4B32EA59AE18B36945D205A876800
6/14/2019 12:54:04 PM - 
6/14/2019 12:54:04 PM - 	Supported Products : 
6/14/2019 12:54:04 PM - 		Microsoft.VisualStudio.Community
6/14/2019 12:54:04 PM - 			Version : [15.0.28307.665,17.0)
6/14/2019 12:54:04 PM - 		Microsoft.VisualStudio.Enterprise
6/14/2019 12:54:04 PM - 			Version : [15.0.28307.665,17.0)
6/14/2019 12:54:04 PM - 		Microsoft.VisualStudio.Pro
6/14/2019 12:54:04 PM - 			Version : [15.0.28307.665,17.0)
6/14/2019 12:54:04 PM - 
6/14/2019 12:54:04 PM - 	References         : 
6/14/2019 12:54:04 PM - 	Prerequisites      : 
6/14/2019 12:54:04 PM - 		-------------------------------------------------------
6/14/2019 12:54:04 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/14/2019 12:54:04 PM - 		Name         : Visual Studio core editor
6/14/2019 12:54:04 PM - 		Version      : [15.0,17.0)
6/14/2019 12:54:04 PM - 
6/14/2019 12:54:04 PM - 		-------------------------------------------------------
6/14/2019 12:54:04 PM - 		Identifier   : Microsoft.VisualStudio.Workload.NetCoreTools
6/14/2019 12:54:04 PM - 		Name         : .NET Core cross-platform development
6/14/2019 12:54:04 PM - 		Version      : [15.0,17.0)
6/14/2019 12:54:04 PM - 
6/14/2019 12:54:04 PM - 		-------------------------------------------------------
6/14/2019 12:54:04 PM - 		Identifier   : Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1
6/14/2019 12:54:04 PM - 		Name         : .NET Core 2.1 development tools
6/14/2019 12:54:04 PM - 		Version      : [15.0,17.0)
6/14/2019 12:54:04 PM - 
6/14/2019 12:54:04 PM - Signature Details...
6/14/2019 12:54:04 PM - 	Extension is signed with a valid signature.
6/14/2019 12:54:04 PM - 
6/14/2019 12:54:04 PM - Searching for applicable products...
6/14/2019 12:54:04 PM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
6/14/2019 12:54:04 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
6/14/2019 12:54:04 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
6/14/2019 12:54:04 PM - Found installed product - Global Location
6/14/2019 12:54:04 PM - Found installed product - ssms
6/14/2019 12:54:04 PM - Found installed product - Visual Studio Enterprise 2017
6/14/2019 12:54:04 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by rustd** [comment]
Sorry to see that you are running into this issue. I transferred this bug in the Model Builder repo. Can you please provide more details here? https://github.com/dotnet/machinelearning-modelbuilder/issues/101
