### ISSUE TITLE
Missing Common directory and ConsoleHelper class

### ISSUE THREAD

**Issue by cyberkoolman** [dotnet/machinelearning-samples#526]
From samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/Program.cs, directory named **Common** isn't available, thus ConsoleHelper.cs is missing.  Though it is stated as OPTIONAL, would like to peek through ConsoleHelper.

**Comment by prathyusha12345** [comment]
the folder named **Common** is shared among all the samples. So when you clone the repo , it should be available in the path https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/common .

Let me know if you still facing any issue.

**Comment by cyberkoolman** [comment]
Oh, thank you.  I was only interested in this isolated example, no issues now.
