### ISSUE TITLE
Need a lightGBM sample

### ISSUE THREAD

**Issue by magicdict** [dotnet/machinelearning-samples#527]
LightGBM is a most important AI function.
Can you give me a lightGBM sample?

**Comment by prathyusha12345** [comment]
we already have a sample using  LightGBM trainer. Please check this sample  https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DatabaseIntegration

Please let me know if you still need any assistance

**Comment by CESARDELATORRE** [comment]
Closing this issue as it was answered and had no further reply.
