### ISSUE TITLE
For any sentiment, I am getting "Toxic Sentiment".

### ISSUE THREAD

**Issue by amit7verma** [dotnet/machinelearning-samples#540]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/consume
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

For whatever sentiment I enter, it shows me result as "Toxic Sentiment". I entered following
"You are cool"
"I am cool"
"I agree"
"You are an angel"

Can someone explain this to me?

Thanks.

**Comment by CESARDELATORRE** [comment]
That's because it is using a very small dataset. Try to use a larger dataset like the ones used in the Samples in this repo.
This was explained in this issue:
https://github.com/dotnet/machinelearning-samples/issues/190

Closing it. Re-open if you still have the same issue with a larger dataset.
