### ISSUE TITLE
Create new sample using TimeSeries Forecasting

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning-samples#552]
Create new sample on TimeSeries Forecasting for "Sales Forecast" to use a trainer based on Time Series instead of Regression - 

Probably, create a simplified version of the eShopDashboard SALES FORECAST using time series:

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Regression-SalesForecast 

Check this TimeSeries Forecasting SAMPLE: https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/TimeSeries/Forecasting.cs

**Comment by colbylwilliams** [comment]
https://github.com/dotnet/machinelearning-samples/pull/592
