### ISSUE TITLE
Create/finish the Anomaly Detection for Fraud detection based on AnomalyDetection-PCA

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning-samples#557]
Create/finish the Anomaly Detection for Fraud detection based on AnomalyDetection-PCA.
Finish current code from Colby:
https://github.com/dotnet/machinelearning-samples/tree/AnomalyDetection_FraudDetection

**Comment by CESARDELATORRE** [comment]
This sample just needs to be tested with ML.NET 1.3 and the bug fixed and then it might need to be updated in order to remove the current 'hack' in the sample.

**Comment by colbylwilliams** [comment]
resolved with https://github.com/dotnet/machinelearning-samples/pull/589
