### ISSUE TITLE
Change repo URL to use HTTPS

### ISSUE THREAD

**Issue by Eilon** [dotnet/machinelearning-samples#567]
Currently it links to http://dot.net/ml, but it should be https://dot.net/ml

![image](https://user-images.githubusercontent.com/202643/61498294-9c4cec00-a977-11e9-91c3-e3b45fb9cbe0.png)

**Comment by CESARDELATORRE** [comment]
Thanks, fixed! 👍

**Comment by Eilon** [comment]
Thanx! 😄
