### ISSUE TITLE
Migrate OnnxObjectDetectionE2EApp to ML.NET v1.2.0 

### ISSUE THREAD

**Issue by bamurtaugh** [dotnet/machinelearning-samples#572]
-Directory.Build.props left with ML.NET v1.1.0, preview v0.13.0
-OnnxObjectDetectionE2EAPP.csproj has combination of hard-coded and dynamic versions 
-When making all versions in both files dynamic, app would crash
-Need to investigate how to make app function with all dynamic, most up-to-date versions of ML.NET

**Comment by paulthedev** [comment]
While this example gets updated, could a more full fleged model like yolov3 be used. 

This would help in understanding how to use complex models with more than one input and output.

Thank you
