### ISSUE TITLE
[choose Scenario]How to  Knowledge Inference

### ISSUE THREAD

**Issue by dwanboweb** [dotnet/machinelearning-samples#573]
I need to train a model using Knowledge Graph(Stored in SQL SERVERL) to predict the possible Relevant thing and their probability，What should I do?I am poor about the marchineLearning,and  I just kown maybe I should use PRA,SFE,OR  TransE?Thank you so much.

**Comment by bamurtaugh** [comment]
Hi @dwanboweb! Could you please provide some more context:

-Can you elaborate on your scenario? What is the "relevant thing" you are trying to predict?
-What do you mean by PRA, SFE, and TransE? PRA appears to be the Pattern Recognition and Applications Lab, and TransE appears to be Translating Embeddings.
-Why/how were you planning to potentially use PRA/SFE/TransE?

**Comment by dwanboweb** [comment]
Yes.The data came from hospital，There are three colums：source，destination，relation.source and destination reference to another table about  symptoms，and the relationship col means the relationsheep between two symptoms.Currently，There are three kind of relationships：is，common caused by，uncommon caused by.Such as
we kown The headache may be caused by a cold，A cold may be caused by a flu virus，How can I predict what caused a headachr and their probability，or predict The probability of getting a headache from a cold？
Thank you very much


发自我的iPhone

------------------ Original ------------------

**Comment by bamurtaugh** [comment]
Thanks for the context! Have you explored multi-class classification? For instance, in our [GitHub Issues Labeler scenario](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler), we train a model based on current GitHub issues and their labels, and the model is then able to predict the label of future issues. 

Perhaps you could train this type of model on your data about symptoms and their causes, and it could then predict the root causes/categories of new symptoms?

**Comment by bamurtaugh** [comment]
Hi @dwanboweb - any update here? Have you resolved your issue? Thanks 😄

**Comment by dwanboweb** [comment]
> Hi @dwanboweb - any update here? Have you resolved your issue? Thanks 😄

year,thank you.
