### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by amin137954** [dotnet/machinelearning-samples#577]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by bamurtaugh** [comment]
Hi @amin137954, can you please elaborate on the problem you are experiencing? If this issue relates to Model Builder rather than ML.NET samples, your issue would be better-suited for the Model Builder repo: https://github.com/dotnet/machinelearning-modelbuilder/issues.

**Comment by bamurtaugh** [comment]
Closing since this issue relates to Model Builder rather than ML.NET samples.
