### ISSUE TITLE
System.InvalidOperationException: 'Operation is not valid due to the current state of the object.'

### ISSUE THREAD

**Issue by SuperRajar** [dotnet/machinelearning-samples#580]
I am trying to do a simple multiclass analyzer for images loaded from a c# list. I get an exception from the Evauate() function whith message "Operation is not valid due to the current state of the object". Does anyone have any thoughts?

```
public class TestImage
        {
            [ColumnName("Label")]
            public float Answer;

            [VectorType(784)]
            public float[] Pixels;

            [ColumnName("Score")]
            [VectorType(10)]
            public float[] Score;

            public float PredictedLabel;
        }

public void Run()
{
            IEnumerable<TestImage> testImages = GetTestImages();

            IDataView data = mlContext.Data.LoadFromEnumerable<TestImage>(testImages);

            DataOperationsCatalog.TrainTestData dataSplit = mlContext.Data.TrainTestSplit(data, testFraction: 0.2);
            IDataView trainData = dataSplit.TrainSet;
            IDataView testData = dataSplit.TestSet;

            var trainer = mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(featureColumnName: "Pixels");
            var dataProcessPipeline = mlContext.Transforms.Conversion.MapValueToKey("Label", "Label");
            dataProcessPipeline.Append(trainer);

            var trainedModel = dataProcessPipeline.Fit(trainData);
                
            var predictions = trainedModel.Transform(testData);
            MulticlassClassificationMetrics metrics = mlContext.MulticlassClassification.Evaluate(data: predictions);
}
```

**Comment by bamurtaugh** [comment]
Hi @SuperRajar - As you may know, a System.InvalidOperationException is thrown when a method of an object is called when the state of the object cannot support the method call. 

Is it possible that the predictions data you are passing to Evaluate() is either empty or otherwise cannot be treated as an IDataView object? When you are calling GetTestImages() and later splitting the data, are both of these operations returning non-null data in a format you're expecting?

**Comment by bamurtaugh** [comment]
@SuperRajar Any update here? Were you able to figure out your problem?

**Comment by bamurtaugh** [comment]
Closing this issue, please let me know if you are still having any trouble and I can re-open it 👍
