### ISSUE TITLE
Any ONNX scoring examples?

### ISSUE THREAD

**Issue by helloguo** [dotnet/machinelearning-samples#64]
We can find how to use ONNX scoring API from https://github.com/dotnet/machinelearning/blob/76dd9235f348aee4fdf7e62a9edf27510f14769b/test/Microsoft.ML.OnnxTransformTest/OnnxTransformTests.cs. However, is there any ONNX scoring examples with some explanation?

**Comment by CESARDELATORRE** [comment]
We'll have a sample on ONNX scoring here soon, it is in the backlog. See the updated table/list here: 
https://github.com/dotnet/machinelearning-samples#deep-learning

**Comment by cosmincatalin** [comment]
I have ONNX scoring working here https://github.com/cosmincatalin/mxnet-onnx-mlnet. I will make a pull request and add documentation soon.

**Comment by CESARDELATORRE** [comment]
@cosmincatalin - In the meantime, I added your sample to the ML.NET Community Samples page, here:

https://github.com/dotnet/machinelearning-samples/blob/master/docs/COMMUNITY-SAMPLES.md

Thanks for sharing the sample! 👍

**Comment by prathyusha12345** [comment]
@helloguo please find the ONNX scoring sample here https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/

Closing the issue. thanks 👍
