### ISSUE TITLE
Typo in the description of the heard-disease example?

### ISSUE THREAD

**Issue by tih2010** [dotnet/machinelearning-samples#641]
Hi!

I am new to ML and like your examples a lot. The description in the of the heard-disease example confuses me:

> This problem is centered around predicting the presence of heart disease based on 14 attributes. To solve this problem, we will build an ML model that takes as **inputs 4 parameters**:

As far as I can see, the input for the model is all 14 attributes, but you say it's only 4... is there a '1' missing in front of the 4?

Best
     Wolfram

**Comment by CESARDELATORRE** [comment]
It's a type, I just fixed it.
Clearly there are 14 attributes, as you can see in the class:

https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/BinaryClassification_HeartDiseaseDetection/HeartDiseaseDetection/HeartDiseaseDetection/DataStructures/HeartData.cs

Thanks for the heads-up! 👍
