### ISSUE TITLE
Exception while Training

### ISSUE THREAD

**Issue by mdboothe** [dotnet/machinelearning-samples#650]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Windows 7 Enterprise 
Visual Studio 2017 

Here is Exception:

Exception occured while exploring pipelines:
Provided label column 'Sentiment' was of type Single, but only type Boolean is allowed.
System.ArgumentException: Provided label column 'Sentiment' was of type Single, but only type Boolean is allowed.
   at Microsoft.ML.CLI.CodeGenerator.CodeGenerationHelper.GenerateCode()
   at Microsoft.ML.CLI.Program.<>c__DisplayClass1_0.<Main>b__0(NewCommandSettings options)
Please see the log file for more info.
Exiting ...

I tried to attach the zipped data file, but cannot tell if it was uploaded.
Below is some sample data.

Sentiment	SentimentText
1	"  ==RUDE== Dude, you are rude upload that carl picture back, or else."
1	  == OK! ==  IM GOING TO VANDALIZE WILD ONES WIKI THEN!!!   
1	"   Stop trolling, zapatancas, calling me a liar merely demonstartes that you arer Zapatancas. You may choose to chase every legitimate editor from this site and ignore me but I am an editor with a record that isnt 99% trolling and therefore my wishes are not to be completely ignored by a sockpuppet like yourself. The consensus is overwhelmingly against you and your trollin g lover Zapatancas,  "
1	  ==You're cool==  You seem like a really cool guy... *bursts out laughing at sarcasm*.
1	" ::::: Why are you threatening me? I'm not being disruptive, its you who is being disruptive.   "
1	  == hey waz up? ==  hey ummm... the fif four fifty one song... was the info inacurate?  did i spell something wrong? hmm... cause i don't think you have a right to delete ANYTHING that is accurate and that peple may want to read about fool. i don't like being pushed around especially by some little boy. got it?
0	" ::::::::::I'm not sure either. I think it has something to do with merely ahistorical vs being derived from pagan myths. Price does believe the latter, I'm not sure about other CMT proponents.   "

Thank you,
Michael Boothe

**Comment by mdboothe** [comment]
Brigit,
I found the issue.
There was an extra record at the end of the data file that was blank.
Apologies, my bad.
Thanks again.
Regards,
Michael Boothe

**Comment by bamurtaugh** [comment]
I'm glad you were able to find the issue! No apologies necessary 😄
