### ISSUE TITLE
Can't find any examples for use ForecastingCatalog

### ISSUE THREAD

**Issue by deniskozlov** [dotnet/machinelearning-samples#657]
Hi. Could You please put some example which will explain how to use ForecastingCatalog?

**Comment by luisquintanilla** [comment]
Hi @deniskozlov 

For forecasting samples, see the following:

- https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/Forecasting_BikeSharingDemand
- https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Forecasting-Sales/src/eShopForecastModelsTrainer/TimeSeriesTrainer (Forecasting Time Series)
- https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Forecasting-Sales/src/eShopForecastModelsTrainer/RegressionTrainer (Forecasting Regression)
