### ISSUE TITLE
MLDotNet Not working with Custom trained model

### ISSUE THREAD

**Issue by thedevankit-0** [dotnet/machinelearning-samples#665]
@codemzs @colbylwilliams 

I have trained my model with python and tensorflow. its working fine with it. but when i tried to used the model with MLDotNet its not working.

I have trained my mdel using inception v3 with transfer learning to identify custom object in an images.

**Comment by ashbhandare** [comment]
Hi @Anki7s , could you share more details on what issue you are facing, the exact error, stack trace and a reproducing sample if possible?

**Comment by Anki7s** [comment]
I have a trained model (Trained using Tensorflow ) which classify some custom images in 4 different categories. The model work fine with python ( as i used python for it to train and to implement) but when i used the model with ML dot Net ( replacing Predefined/ Given model  file the one with .pb extension) its not working.  DO i need to trained my model differently for ml dot net to used it with dotnet ?

**Comment by IveJ** [comment]
Hi Issuer,

Plz show err. msg. for easily checking details.

**Comment by luisquintanilla** [comment]
Hi @thedevankit-0 

Sorry to hear you ran into issues. ML.NET now supports transfer learning for image classification. See this guide to learn how to do so. https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning. Inceptionv3 is one of the supported architectures. Please feel free to open any issues in the [dotnet/machinelearning](https://github.com/dotnet/machinelearning) repo if you run into any issues with the API.
