### ISSUE TITLE
Demo for remove watermark from image

### ISSUE THREAD

**Issue by Edward-Zhou** [dotnet/machinelearning-samples#676]
For `Tensorflow`, there is fully convolutional deep neural network to remove transparent overlays from images, is there any plan to implement this in ML.NET?

**Comment by CESARDELATORRE** [comment]
If you just want to use that TensorFlow model (.pb) in .NET you can already load it and use it like in this sample:

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow

Is that what you mean?

If you mean re-training and doing transfer-learning from that model (to remove transparent overlays) for additional particular cases, we don't have that in our roadmap. So far, re-training by internally using transfer learning with:
- Image Classification
- Object Detection

Can you elaborate a bit further what is what you want to do?

Thanks for your feedback.

**Comment by luisquintanilla** [comment]
Closing this issue since there is a response to the question and has since been inactive.
