### ISSUE TITLE
First tutorial, doesn't compile

### ISSUE THREAD

**Issue by fradav** [dotnet/machinelearning-samples#681]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Windows 10 1903
dotnet core 3.0
Solution created with the option "project in the same folder than solution"

Unable to compile myMLApp, as shows :
![image](https://user-images.githubusercontent.com/701587/66377292-97656a80-e9b1-11e9-886f-91e6b759effc.png)

![image](https://user-images.githubusercontent.com/701587/66377279-8fa5c600-e9b1-11e9-8aa0-e48bb5e61e5c.png)

**Comment by fradav** [comment]
As I suspected, the problem goes away if you put solution/project in different directories at creation.
This should be documented.

**Comment by briacht** [comment]
Thanks for the feedback! I added a step to make it more clear in the tutorial:
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create

**Comment by fradav** [comment]
Perfect.
