### ISSUE TITLE
ML.NET ISSUE

### ISSUE THREAD

**Issue by Kiansniper2005** [dotnet/machinelearning-samples#707]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I right click on mlMLApp and add, there isn't an option there called machine learning. I ran the only .exe in the Microsoft.ML.ModelBuilder. The .exe was called: lightgbm.exe.

**Comment by rustd** [comment]
Issue moved to [dotnet/machinelearning-modelbuilder #299](https://github.com/dotnet/machinelearning-modelbuilder/issues/299) via [**ZenHub**](https://www.zenhub.com/)
