### ISSUE TITLE
Visual Studio crashes after adding the example .tsv file

### ISSUE THREAD

**Issue by Sebastian949494** [dotnet/machinelearning-samples#709]
Problem related to the following link:
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data

When I created a .tsv file from the dataset with Visual Studio 2019 as shown in the example, the IDE crashed without any further information.

Best regards,
Sebastian

**Comment by rustd** [comment]
Issue moved to [dotnet/machinelearning-modelbuilder #298](https://github.com/dotnet/machinelearning-modelbuilder/issues/298) via [**ZenHub**](https://www.zenhub.com/)
