### ISSUE TITLE
Extra LpNorm

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-samples#710]
The LPNorm here is extraneous as an LpNorm is already included in the FeaturizeText by default:
https://github.com/dotnet/machinelearning-samples/blob/c3b14f76b1fd88eb75015cb1198da52ec17c967d/samples/csharp/getting-started/BinaryClassification_SpamDetection/SpamDetectionConsoleApp/Program.cs#L41-L49

If you want it to be explicit, you can call out the LpNorm within the FeaturizeText  options, but it runs a L2 norm by default. It's unnecessary though has the pedagogical aspect of letting users know it's available to change.

Work:
* Remove the `.Append(mlContext.Transforms.NormalizeLpNorm("Features", "Features"))` line

**Comment by AnoojNair** [comment]
@justinormont - Happy to do this one.

**Comment by justinormont** [comment]
@AnoojNair : Go ahead. Can you also place the `LpNorm` in the `FeaturizeText` options? That way it's still visible to users. 

The `LpNorm` is exposed as the `Norm` parameter in the `FeaturizeText` options object, and you can set it to `NormFunction.L2`. 

`TextFeaturizingEstimator.Options` reference: https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.text.textfeaturizingestimator.options?view=ml-dotnet
