### ISSUE TITLE
visual studio stops working when clicked on start training

### ISSUE THREAD

**Issue by juzer-hakimji** [dotnet/machinelearning-samples#712]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

whenever i click on start training visual studio stops working and then it restarts please look into this issue, my VS version is 15.9.13

**Comment by rustd** [comment]
Issue moved to [dotnet/machinelearning-modelbuilder #296](https://github.com/dotnet/machinelearning-modelbuilder/issues/296) via [**ZenHub**](https://www.zenhub.com/)

**Comment by juzer-hakimji** [comment]
Hey,
I am using windows 10  and i followed the exact same steps as in the tutorial on ml.net on microsoft website with exact same code but as soon as i hit start training it shows "Visual studio has stopped working" and then "visual studio is restarting" and then it restarts, my Visual studio version is 15.9.13

**Comment by juzer-hakimji** [comment]
I have updated my VS version to 15.9.17 community edition and still the problem exists
