### ISSUE TITLE
Windows 10, Visual studio 2019, 

### ISSUE THREAD

**Issue by amazink** [dotnet/machinelearning-samples#718]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows
I keep on getting the following error code even when I follow all the steps to the latter.
Error	CS0579	Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute	myMLApp

**Comment by luisquintanilla** [comment]
Hi @amazink 

Sorry to hear you are experiencing issues. Have you tried the latest version of Model Builder / getting-started guide? Closing this issue for now since there are new versions of Model Builder. Please feel free to open another issue if you still run into problems.
