### ISSUE TITLE
VS 2019 Enterprise freeze when choosing the dataset file

### ISSUE THREAD

**Issue by Eyad-Mohammed-Osama** [dotnet/machinelearning-samples#721]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

So i was following the instructions on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data to insert the dataset, but when i choose the dataset tsv file from the dialog box Visual Studio freeze for a couple of minutes then it shutdown and restart, that's all the problem.
I'm using Visual Studio 2019 Enterprise on Windows 10.
That's all the information i have, i can provide anymore info if necessary.

**Comment by luisquintanilla** [comment]
Hi @Eyad-Mohammed-Osama ,

Sorry to hear you experienced issues. Have you tried the latest version of Model Builder/ getting started guide. Closing for now since there are new versions of Model Builder. Please feel free to open another issue if you still run into issues.
