### ISSUE TITLE
VS 2019, Training error

### ISSUE THREAD

**Issue by mattisking** [dotnet/machinelearning-samples#724]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Using online demo, training step with downloaded data file, wikipedia-detox-250-line-data.tsv, every single time training fails within 1 second: 
Loading this assembly would produce a different grant set from other instances. HRESULT: 0x80131401

Windows 10: 1809
VS 2019: 16.3.6

I also have Visual Studio 2017. The same set of steps with same training file works fine, same machine.

**Comment by luisquintanilla** [comment]
Hi @mattisking 

Sorry to hear you experienced issues. Have you tried the latest version of Model Builder / the get-started guide? Please reach out if you still run into issues. Closing this issue since there are new versions of Model Builder that may have addressed this issue.
