### ISSUE TITLE
DatabaseSource requires new SqlConnection even if an open Connection exists!

### ISSUE THREAD

**Issue by FranzBl** [dotnet/machinelearning-samples#727]
I already posted this issue in the thread about DatabaseLoader (that is now closed). Since no one gave a comment to this, perhaps it was overseen. In my view it is a design problem in the implementation of the ML-SQL-Interface:

DatabaseLoader requires its own database connection:

DatabaseSource dbSource = new DatabaseSource(SqlClientFactory.Instance, connectionString, sqlCommand);
DatabaseLoader loader = mlContext.Data.CreateDatabaseLoader();

I suppose the idea behind this is that software developers will train their models in standalone programs that are not delivered with their software, to which only the trained models are passed.
I would like to integrate model training in a larger Windows forms solution. There the model will not be static, but the training data will grow with time, when new values are detected and stored in the database. So a regular training of the model will be required to enhance performance. This should be done within the Windows program, whenever a new chunk of data is stored in the database.
In this Windows program a SqlConnection is open all the time, from beginning to the end. So wouldn't if make sense if DatabaseSource would have an additional constructor to pass this existing SqlConnection instead of opening a new one?
It is clear that during the time when DatabaseLoader reads the data table, there should be no new data to be stored in the database, to avoid interlock effects. But knowing this, it might be implemented without problems. New data for the database are produced only in certain time windows during day, and the model training could take place at night.
Will there be no problem at all to open a new SqlConnection within a program that already has another one open?

**Comment by FranzBl** [comment]
--> "What's the reason you want to have a "a SqlConnection is open all the time, from beginning to the end of the WinForms app"?"

The program inquires stock values from the web in real time, and every few seconds asks for new values that are stored straightforward in the database. I suppose it would reduce performance if I would always open and close SqlConnection every time a new value is detected. This may be necessary probably several times for each inquiry of the stock list from the web since several values might have changed.
Of course, within this event Queue any model Training is deactivated for the user. Training should occur only when such a "watch loop" has come to an end. Therefore I might Change the program so that the SqlConnection is open only during the watch loop and is closed afterwards. If the day is over, the user might use the new values for additional Training and open a new database Connection to do this. Ok.

**Comment by CESARDELATORRE** [comment]
Closing the issue if it's been clarified, ok? Thanks! 👍

**Comment by FranzBl** [comment]
Ok
