### ISSUE TITLE
Show metrics and current iteration (epoch) during training 

### ISSUE THREAD

**Issue by bhrnjica** [dotnet/machinelearning-samples#743]
Is it possible to get training progress, so I can show on the Console how my training is going (training metrics) for each iteration?

**Comment by ashbhandare** [comment]
For ImageClassification training, you can follow https://github.com/dotnet/machinelearning-samples/blob/a9802000e1aa55a67f604a677183768d7eb3a327/samples/csharp/getting-started/DeepLearning_ImageClassification_Training/ImageClassification.Train/Program.cs#L78 
to print the training metrics after every epoch.
