### ISSUE TITLE
Still database problem with Microsoft.ML (#722)

### ISSUE THREAD

**Issue by FranzBl** [dotnet/machinelearning-samples#744]
Now that issue #722 is closed and a new version of Microsoft.ML is released, indeed the problem with single data types is solved. When I open the database connection, all table columns are properly transferred to the IDataview.
Unfortunately, whenever I want to use the values from the dataView, I get an uncaught exception. In the following screenshot example I only wanted to extract an enumerable:

![image](https://user-images.githubusercontent.com/44602645/69067280-18893600-0a23-11ea-9ff6-c75599391404.png)

The same happens if I try to evaluate at once.
It looks as if the database loader transfers the column schema only, but for access to the values a new database call is needed (with a new database connection).
How to fix this? Should I establish a new database connection before using the DataView? Or is this another bug?

**Comment by FranzBl** [comment]
To tell the truth: Indeed it looks like access to the enumerable would try to establish a new connection itself, while the old one is still open. Should I close it after creation of the dataView?

**Comment by ashbhandare** [comment]
Hi @FranzBl , I am afraid I do not understand the exception message as it is not in English.
Other than that, I tried and could run this without an exception:

```
var loader = mlContext.Data.CreateDatabaseLoader<IrisDataWithLoadColumnName>();

            var databaseSource = new DatabaseSource(SqlClientFactory.Instance, connectionString, commandText);

            var trainingData = loader.Load(databaseSource);

            var ipDataEnum = mlContext.Data.CreateEnumerable<IrisDataWithLoadColumnName>(trainingData, reuseRowObject: true);

            foreach(IrisDataWithLoadColumnName row in ipDataEnum)
            {
                Console.WriteLine(row);
            }
```

**Comment by FranzBl** [comment]
Sorry, I have German version of MS Visual Studio installed, but i may translate the exception, but sometimes it is quite good to translate ... since you must look more thoroughly for that what is written there.

I found out there was a mismatch between D: and C: drives. Not so long ago I moved the database software to the D: drive since C: is a SSD drive which has only 250 GB and there was not enough space... The program still was not adapted.... My fault.

But - later on this exception didn't occur, but another one did. Obviously the database loader is unable to convert SQL Datetime records to string. If this is as should be, I have to redesign my database and to store all Datetime values as strings?

**Comment by ashbhandare** [comment]
Could you create a separate issue, with the new exception in English, and include a reproducer (the sample with the necessary dummy data files)?

**Comment by FranzBl** [comment]
I suppose I will now be able to solve the problem myself, thank you.

**Comment by FranzBl** [comment]
The Datetime problem I solved, I suppose. But after these fields in the database there are float values, and they lead to a next problem in reading database data. I enclose some screenshots:

1. The ModelInput declaration:
![image](https://user-images.githubusercontent.com/44602645/69142508-3f00ad00-0ac7-11ea-89c6-532b894794ed.png)

2. This corresponds with the table layout in the database:
![image](https://user-images.githubusercontent.com/44602645/69142578-66577a00-0ac7-11ea-9e80-9802b4baff26.png)

3. When the database loader finished, the schema of trainingDataView shows the correct data types, in VS debugger:
![image](https://user-images.githubusercontent.com/44602645/69142750-c0583f80-0ac7-11ea-8d1a-598df0edf273.png)

4. But when I try to print inputDataEnumerable, a cast exception occurs:
![image](https://user-images.githubusercontent.com/44602645/69142875-03b2ae00-0ac8-11ea-9e8c-c1bbb88cac23.png)

At this point I don't see any programming error from my side. If the database contains only float values (screenshot 2), and if these values are declared properly as float in ModelInput class (screenshot 1), why the hell someone finds type "double" in the foreach loop? As far as I know, the inputDataEnumerable should contain members of type ModelInput. Therefore all float values should be indeed float and not double. Where the "double" comes from?

**Comment by eerhardt** [comment]
@FranzBl - check out https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-data-type-mappings. You will see something that has confused me in the past as well:

SQL Server Database Engine type | .NET Framework type | SqlDbType enumeration | SqlDataReader SqlTypes typed accessor | DbType enumeration | SqlDataReader DbType typed accessor
-- | -- | -- | -- | -- | --
float | Double | Float | GetSqlDouble | Double
real | Single | Real | GetSqlSingle | Single

As you can see with this mapping, the `float` column in SQL Server is mapped to `System.Double` in .NET. If you want to have a `System.Single` in .NET (what C# calls a `float`), the SQL Server column should be a `real` type. I know, it isn't logical at all, but that is how the systems named their types. I find this table super helpful in times like this.

**Comment by ashbhandare** [comment]
Could you try to isolate which column is causing this issue?

**Comment by ashbhandare** [comment]
@FranzBl Could you confirm that changing the data type according to the sql server datatype mappings solved your issue?

**Comment by FranzBl** [comment]
> @FranzBl - check out https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-data-type-mappings. You will see something that has confused me in the past as well:
> 
> SQL Server Database Engine type	.NET Framework type	SqlDbType enumeration	SqlDataReader SqlTypes typed accessor	DbType enumeration	SqlDataReader DbType typed accessor
> float	Double	Float	GetSqlDouble	Double	
> real	Single	Real	GetSqlSingle	Single	
> As you can see with this mapping, the `float` column in SQL Server is mapped to `System.Double` in .NET. If you want to have a `System.Single` in .NET (what C# calls a `float`), the SQL Server column should be a `real` type. I know, it isn't logical at all, but that is how the systems named their types. I find this table super helpful in times like this.

Oops!

**Comment by eerhardt** [comment]
Sounds like this issue is resolved. Feel free to re-open it if your questions haven't been answered.

**Comment by FranzBl** [comment]
Sorry I couldn't answer earlier. To change column type of database, I had to change the program that generates it (in many places) and to setup a new database.
Indeed with data type real instead of float the program works incl. evaluating, training etc. With one exception: Trying to save the model to a zip file for later use on end fails. Reason: One table column is type datetime (in SQL). During generation of the data view this is converted into string, and training works. Saving the model attempts to change these column data back from string to datetime, so an exception is thrown.
Is this as should be? If model saving tries to reconstruct the original data types, so I think it should be able to parse a string as datetime.
In fact I could store the timestamps as simple strings in the database. But many database queries use datetime arithmetics, e. g. retrieving all data between two timestamps (SQL can do this very easy, while the date arithmetics on strings would be a little tricky).
