### ISSUE TITLE
Newly trained TensorFlow model isn't saving to disc in Image Classification Model Training sample

### ISSUE THREAD

**Issue by imperium02** [dotnet/machinelearning-samples#747]
### System information

- **Windows 10/1903**:
- **.NET Version 3.0.100**: 

### Issue

- **What did you do?**
I ran sample Image classification training project from:
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Training
and started ImageClassification.Train

- **What happened?**
The program ran with no problems and ended with no error messages.

- **What did you expect?**
I expected to find newly trained Tensorflow model in bin\Debug\netcoreapp2.1 because that path is shown in project's README but it wasn't there and I couldn't find it anywhere else. The ML.NET model in zip format saved properly in assets\outputs.

**Comment by ashbhandare** [comment]
@imperium02 By default, the trained model is saved in a temp folder, which you can see from the logs:
```
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  34, Accuracy:  0.8333333
Saver not created because there are no variables in the graph to restore
Restoring parameters from C:\Users\..\AppData\Local\Temp\wyjrturn.cnh\custom_retrained_model_based_on_resnet_v2_50_299.meta
Froze 2 variables.
Converted 2 variables to const ops.
```
You can specifically set the location where you want the model to be saved by setting the options.WorkspacePath parameter in ImageClassificationTrainer.Options().
