### ISSUE TITLE
[Image Classification Model Training] sample does not generate the .pb file

### ISSUE THREAD

**Issue by Ghisso** [dotnet/machinelearning-samples#749]
I was working on an image classification project and trained a model following the [Image Classification Model Training] sample. The training and models work fine. However, I wanted to use the model in Python and tried to convert to ONNX but it didn't work (this is a separate issue but I get : Unhandled Exception: System.InvalidOperationException: The targeted pipeline can not be fully converted into a well-defined ONNX model. Please check if all steps in that pipeline are convertible to ONNX and all necessary variables are not dropped (via command line arguments) ).

I thought ok I'll just use directly the .pb files. However, I couldn't find them in the output folder.
I thought I made a mistake somewhere, but when checking the code of the sample, it is clearly written in ImageClassification.Train.Program.cs on line 104 : "// 8. Save the model to assets/outputs (You get ML.NET .zip model file and TensorFlow .pb model file)".
I ran the sample and it didn't produce the pb file either.
So has the save function been changed to no longer produce the pb file? And how can I get the pb file? I tried unzipping the model file and renamed the TFModel file to TFModel.pb but Netron couldn't open it.

**Comment by luisquintanilla** [comment]
Hi @Ghisso 

To get the `.pb` version of the model, you need to specify the `WorkspacePath` parameter to your `ImageClassification` trainer as seen in this example. https://github.com/dotnet/machinelearning-samples/blob/ddbe84ff23943fdc528178a17dc823f5d4802705/samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification_Binary/Program.cs#L56

Here is the accompanying tutorial for this sample. https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning

For more information, here is also the API docs for the trainer options.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.vision.imageclassificationtrainer.options?view=ml-dotnet
