### ISSUE TITLE
onnx model image classify get exception

### ISSUE THREAD

**Issue by ricklina90** [dotnet/machinelearning-samples#750]
Hi,
     I trying to modify https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx sample code use my onnx model to classify my image. When I want to get image result 
from OnnxModelScorer.cs, I meet exception like
 {"Splitter/consolidator worker encountered exception while consuming source data"}

Could any one tell me how to improve my code?

Thanks for your attention,
Rick

Here is my model
![model](https://user-images.githubusercontent.com/53546552/69841709-4419e500-129b-11ea-8e0c-e9bb50203539.png)

//input_image
![image](https://user-images.githubusercontent.com/53546552/69848392-f7db9e80-12b4-11ea-83e3-fd157a17876c.png)

//Add
![image](https://user-images.githubusercontent.com/53546552/69848499-396c4980-12b5-11ea-9a80-8a326b7f0ce4.png)

//input_label
![image](https://user-images.githubusercontent.com/53546552/69848548-59037200-12b5-11ea-9866-47f1cd03590b.png)

//Concat
![image](https://user-images.githubusercontent.com/53546552/69848590-720c2300-12b5-11ea-9ed5-baabad91163a.png)

//concatenate_1
![image](https://user-images.githubusercontent.com/53546552/69848611-82bc9900-12b5-11ea-996c-cc4136a52c02.png)

According to my model, I modify my relate .cs file as below

 ImageNetPrediction.cs

    public class ImageNetPrediction
    {
        [ColumnName("concatenate_1")]
        public string PredictedLabels;
    }

ImageNetData.cs

    public class ImageNetData
    {
        [LoadColumn(0)]
        public string input_image;
        public static IEnumerable<ImageNetData> ReadFromFile(string imageFolder)
        {
            return Directory .GetFiles(imageFolder)
                     .Where(filePath => Path.GetExtension(filePath) != ".md")
                     .Select(filePath => new ImageNetData { input_image = filePath });
        }
    }

OnnxModelScorer.cs

    public struct ImageNetSettings
    {
     public const int imageHeight = 224;
     public const int imageWidth = 224;
    }

    private ITransformer LoadModel(string modelLocation)
    {
            Console.WriteLine("Read model");
            Console.WriteLine($"Model location: {modelLocation}");
            Console.WriteLine($"Default parameters: image size=({ImageNetSettings.imageWidth}, 
                                             {ImageNetSettings.imageHeight})");

            var pipeline = mlContext.Transforms.LoadImages(outputColumnName: "input_image",     imageFolder: "", inputColumnName: nameof(ImageNetData.input_image))
                           .Append(mlContext.Transforms.ResizeImages(outputColumnName: "input_image", imageWidth: ImageNetSettings.imageWidth, imageHeight: ImageNetSettings.imageHeight, inputColumnName: "input_image"))
                           .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "input_image"))
                           .Append(mlContext.Transforms.ApplyOnnxModel(modelFile: modelLocation, outputColumnNames: new[] { TinyYoloModelSettings.ModelOutput }, inputColumnNames: new[] { TinyYoloModelSettings.ModelInput}));

            // Fit scoring pipeline
            var model = pipeline.Fit(data);
            return model;
    }

    private IEnumerable<float[]> PredictDataUsingModel(IDataView testData, ITransformer model)
    {
            Console.WriteLine($"Images location: {imagesFolder}");
            Console.WriteLine("");
            Console.WriteLine("=====Identify the objects in the images=====");
            Console.WriteLine("");

            IDataView scoredData = model.Transform(testData);

            IEnumerable<float[]> probabilities = scoredData.GetColumn<float[]>(TinyYoloModelSettings.ModelOutput);

           //get image result
            var result = probabilities.ElementAt(0);

            return probabilities;
    }

**Comment by IveJ** [comment]
Hi freind,

A Graphics object cannot be created from an image that has an indexed pixel
format.

 If you have tensorflow transfomer please make sure to have
addBatchDimensionInput:
true as an argument. See below for an example:

var pipeline = mlContext.Model.LoadTensorFlowModel(modelLocation).ScoreTensorFlowModel(
                new[] { nameof(OutputScores.output) },
                new[] { nameof(TensorData.input) },
addBatchDimensionInput: true);

**Comment by ricklina90** [comment]
@IveJ  Thanks for the quick reply.

I trying to change my model and my pipeline as below.
It works fine. Thanks for the tip.

Rick

            var pipeline = mlContext.Transforms.LoadImages(outputColumnName: "conv2d_1_input", imageFolder: "", inputColumnName: nameof(ImageNetData.conv2d_1_input))
                           .Append(mlContext.Transforms.ResizeImages(outputColumnName: "conv2d_1_input", imageWidth: ImageNetSettings.imageWidth, imageHeight: ImageNetSettings.imageHeight, inputColumnName: "conv2d_1_input"))
                           .Append(mlContext.Transforms.ConvertToGrayscale(outputColumnName: "conv2d_1_input", inputColumnName: nameof(ImageNetData.conv2d_1_input)))
                           .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "conv2d_1_input", colorsToExtract: ImagePixelExtractingEstimator.ColorBits.Red, scaleImage: ((float)(1.0 / 255.0))))
                           .Append(mlContext.Transforms.ApplyOnnxModel(modelFile: modelLocation, outputColumnNames: new[] { TinyYoloModelSettings.ModelOutput }, inputColumnNames: new[] { TinyYoloModelSettings.ModelInput }));

my model
![trip_Ost_29](https://user-images.githubusercontent.com/53546552/69947097-eb12b100-1527-11ea-9289-6dd0823e29a3.png)

**Comment by IveJ** [comment]
Thanks Rick a lot, community behide the people.

**Comment by luisquintanilla** [comment]
Glad to hear it's working now @ricklina90 . Thanks @IveJ for the suggestions.
