### ISSUE TITLE
InvalidDataException: End of Central Directory record could not be found. Error when loading custom trained model from Azure Blob Storage in ASP.NET Core Web API

### ISSUE THREAD

**Issue by willvelida** [dotnet/machinelearning-samples#754]
I have trained a regression model and I have uploaded it to a container in Blob Storage. This is the method that I use to upload the model to blob storage:

`public async Task TrainAndUploadModelAsync(MLContext mlContext, string dataPath, CloudBlobContainer container)
        {
            IDataView dataView = mlContext.Data.LoadFromTextFile<TaxiTrip>(dataPath, hasHeader: true, separatorChar: ',');

            var pipeline = mlContext.Transforms.CopyColumns("Label", "FareAmount")
                .Append(mlContext.Transforms.Categorical.OneHotEncoding("VendorIdEncoded", "VendorId"))
                .Append(mlContext.Transforms.Categorical.OneHotEncoding("RateCodeEncoded", "RateCode"))
                .Append(mlContext.Transforms.Categorical.OneHotEncoding("PaymentTypeEncoded", "PaymentType"))
                .Append(mlContext.Transforms.Concatenate("Features", "VendorIdEncoded", "RateCodeEncoded", "PassengerCount", "TripTime", "TripDistance", "PaymentTypeEncoded"))
                .Append(mlContext.Regression.Trainers.FastTree());

            var model = pipeline.Fit(dataView);

            using (var stream = new MemoryStream())
            {
                mlContext.Model.Save(model, dataView.Schema, stream);
                stream.Position = 0;
                await _azureStorageHelpers.UploadBlobToStorage(container, "Model.zip", stream);
            }
        }`

Now I'm trying to consume that model via a ASP.NET Core Web API like so:

`services.AddPredictionEnginePool<TaxiTrip, TaxiTripFarePrediction>()
                .FromUri(
                modelName: "TaxiTripFarePredictionModel",
                uri: "https://velidastorage.blob.core.windows.net/mlmodels/model.zip",
                period: TimeSpan.FromSeconds(15));`

Then I'm calling a POST Method to make a prediction on the following JSON payload

`{
    "VendorId": "VTS",
    "RateCode": "1",
    "PassengerCount": 1,
    "TripTime": 1140,
    "TripDistance": 3.75,
    "PaymentType": "CRD",
    "FareAmount": 0
}`

And the POST Method:

`[HttpPost]
        public ActionResult<string> Post([FromBody] TaxiTrip input)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            TaxiTripFarePrediction prediction = _predictionEnginePool.Predict(modelName: "TaxiTripFarePredictionModel", example: input);

            string predictedFareAmount = prediction.FareAmount.ToString();

            return Ok(predictedFareAmount);
        }`

However, when I call the PredictionEnginePool.Predict() method, I get the following error:

`System.FormatException: 'Failed to open a zip archive'. Inner Exception InvalidDataException: End of Central Directory record could not be found.
`

I'm not sure where I am going wrong here. I'm wondering whether or not the model has been uploaded correctly, or whether the Web API is having difficulty downloading the blob.

Steps to reproduce:

1. Fork the following repository: https://github.com/willvelida/PricePredictor/tree/feature/api
2. Run the ModelTrainer console application to train the model.
3. Run the API with the above payload to reproduce the error.

The full code for the repository can be found here: https://github.com/willvelida/PricePredictor

**Comment by willvelida** [comment]
Closing issue in sample repo and raised in main machinelearning repo: https://github.com/dotnet/machinelearning/issues/4541

**Comment by IveJ** [comment]
Hi Will,

Should we consider Authorize request to Azure storage, to access scheme
https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-requests-to-azure-storage

Or

Use GetOutputScheme() method to comfirm dataviewscheme produce by the loader

https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.textloader?view=ml-dotnet
