### ISSUE TITLE
DeepLearning_TensorFlowEstimator doesn't work for only two classes

### ISSUE THREAD

**Issue by st170911** [dotnet/machinelearning-samples#756]
Hi, I'm trying to classify images into two classes, but it gives me an array out of bounds exception, after the evaluation of the model, when trying to save it (I guess).
It works fine with three classes.

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.Generic.IReadOnlyList<T>.get_Item(Int32 index)
   at Common.ConsoleHelper.PrintMultiClassClassificationMetrics(String name, MulticlassClassificationMetrics metrics) in [...]\machinelearning-samples-master\samples\csharp\common\ConsoleHelper.cs:line 79
   at ImageClassification.Model.ModelBuilder.BuildAndTrain(IEnumerable`1 imageSet) in [...]\machinelearning-samples-master\samples\csharp\getting-started\DeepLearning_TensorFlowEstimator\ImageClassification.Train\Model\ModelBuilder.cs:line 112
   at ImageClassification.Train.Program.Main(String[] args) in [...]\machinelearning-samples-master\samples\csharp\getting-started\DeepLearning_TensorFlowEstimator\ImageClassification.Train\Program.cs:line 42
```

Visual Studio 2019 on Windows 10

**Comment by CESARDELATORRE** [comment]
Interesting.. Adding @codemzs. I think this can be a simple bug when printing the METRICS out in the method ConsoleHelper.PrintMultiClassClassificationMetrics(). Not sure?

I think you are using the "Model composition approach here in this sample?"
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator

For training an Image Classifer, I would recommend the native DNN Transfer Learning approach in this other sample:
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Training

If you want to know the differences between those approaches, read this blog post:
https://devblogs.microsoft.com/cesardelatorre/training-image-classification-recognition-models-based-on-deep-learning-transfer-learning-with-ml-net/

In any case, @codemzs, someone from the team would need to take a look to the exception.

**Comment by st170911** [comment]
Thanks for the quick reply!

> I think you are using the "Model composition approach here in this sample?"
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator

Yes, that's the one I'm using.

> For training an Image Classifer, I would recommend the native DNN Transfer Learning approach in this other sample:
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Training

I tried that one too, but it doesn't work either.
It throws me a copy error.

`1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4570,5): error MSB3021: File "[...]\machinelearning-samples-master\samples\csharp\getting-started\DeepLearning_ImageClassification_Training\ImageClassification.Train\assets\inputs\images-for-predictions\FlowersForPredictions\RareThreeSpiralledRose.png" could not be copied to "bin\Debug\netcoreapp2.1\assets\inputs\images-for-predictions\FlowersForPredictions\RareThreeSpiralledRose.png". A part of the path "bin\Debug\netcoreapp2.1\assets\inputs\images-for-predictions\FlowersForPredictions\RareThreeSpiralledRose.png" could not be found.`
(roughly translated)

**Comment by CESARDELATORRE** [comment]
@codemzs - Any limitation when using only two classes?

**Comment by st170911** [comment]
I was looking into the metrics again (as I mentioned, I thought the issue was saving the model before) and the solution is just commenting one line out.

```
public static void PrintMultiClassClassificationMetrics(string name, MulticlassClassificationMetrics metrics)
        {
            Console.WriteLine($"************************************************************");
            Console.WriteLine($"*    Metrics for {name} multi-class classification model   ");
            Console.WriteLine($"*-----------------------------------------------------------");
            Console.WriteLine($"    AccuracyMacro = {metrics.MacroAccuracy:0.####}, a value between 0 and 1, the closer to 1, the better");
            Console.WriteLine($"    AccuracyMicro = {metrics.MicroAccuracy:0.####}, a value between 0 and 1, the closer to 1, the better");
            Console.WriteLine($"    LogLoss = {metrics.LogLoss:0.####}, the closer to 0, the better");
            Console.WriteLine($"    LogLoss for class 1 = {metrics.PerClassLogLoss[0]:0.####}, the closer to 0, the better");
            Console.WriteLine($"    LogLoss for class 2 = {metrics.PerClassLogLoss[1]:0.####}, the closer to 0, the better");
            //Console.WriteLine($"    LogLoss for class 3 = {metrics.PerClassLogLoss[2]:0.####}, the closer to 0, the better");
            Console.WriteLine($"************************************************************");
        }
```
(Could have thought of that earlier..)

Thank you a lot for your help and time, I really appreciate it.
