### ISSUE TITLE
How can I convert yolov3_custom.weight to onnx model?

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [dotnet/machinelearning-samples#769]
I have a model yolov3 trained on my own dataset which included: obj.names have 2 classes, obj.cfg, and .weights file. But I don't know how to covert this model to onnx for using this tutorial: https://github.com/nguyenanhtuan1008/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx

**Comment by luisquintanilla** [comment]
Hi @nguyenanhtuan1008 

Thank you for your question. Depending on the framework you trained your model with, I would suggest taking a look at some of these guides.

https://github.com/onnx/tutorials#converting-to-onnx-format
