### ISSUE TITLE
Image Classification with AutoML score is 1 or 0 and not in percentage

### ISSUE THREAD

**Issue by maddionacsmt** [dotnet/machinelearning-samples#780]
I have created a model using VisualStudio AutoML (v 1.4.0) for image classification. 
I've given two classes of images with ~1000 and ~500 images. 
The model works and predicts a output when I use it but the problem is that the scores are always 1 or 0, and I can't see the percentage. 
I would like to see something like [0.65, 0.35] and not [1, 0]. 
I've searched on documentation and try to look at the auto generated code to see if there is a specific option to set but I haven't found what I need. 
Does anyone have any advice?

**Comment by luisquintanilla** [comment]
Hi @maddionacsmt 

The `Score` column output as part of a prediction should provide these values for you. Have you tried with other datasets and are you seeing the same result?

**Comment by maddionacsmt** [comment]
Hi @luisquintanilla,
thank you for your answer. Yes I use the Score column but it always contains 1 or 0 and it doesn't contain the decimal values as expected.
I've tried with the official (flowers) example too:
When I use the already trained model (that is given in the example) it works correctly, I have decimal values in the Score but when I train the model by myself (with the code given in the example) the prediction gives me only 1 or 0.
I can't understand where is the problem. I need to see the Score in percentage for my purpose.

**Comment by luisquintanilla** [comment]
Model Builder recently released a new version.

https://marketplace.visualstudio.com/items?itemName=MLNET.07

Can you try using the latest version to see whether this is still an issue. If it still persists, I would suggest raising an issue on the repo for the tool. https://github.com/dotnet/machinelearning-modelbuilder/issues

**Comment by maddionacsmt** [comment]
Hi @luisquintanilla, 
after the update I can see the values in percentage in a new AutoML generate code! Now I have to import in my project. Thank you for your help!
