### ISSUE TITLE
Unable to cast object of type 'System.Int32' to type 'System.Int64'.' (MLTrainer: Matrix Factorization (Recommendation))

### ISSUE THREAD

**Issue by kamranalam27** [dotnet/machinelearning-samples#784]
Model:
[KeyType(count: 15767)]
        public uint ProductID { get; set; }
        [KeyType(count: 15767)]
        public uint CombinedProductID { get; set; }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public uint InvoiceID { get; set; }
In Database:
ProductID is bigint
CombinedProductID is also bigint
InvoiceID   is also bigint

**Comment by kamranalam27** [comment]
which datatype should have to declare in database for uinnt.

**Comment by luisquintanilla** [comment]
Hi @kamranalam27 ,

Please take a look at this guide when working with data from a database. 

https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net#load-data-from-a-relational-database

From the article:

> Numerical data that is not of type Real has to be converted to Real. The Real type is represented ?as a single-precision floating-point value or Single, the input type expected by ML.NET algorithms. In this sample, the NumBed column is an integer in the database. Using the CAST built-in function, it's converted to Real. Because the Price property is already of type Real it is loaded as is.

**Comment by luisquintanilla** [comment]
Hi @kamranalam27 ,

Were you able to solve your issue? If you are having issue with the API, I'd suggest raising an issue in the ML.NET Repo: [dotnet/machinelearning](https://github.com/dotnet/machinelearning)
