### ISSUE TITLE
Poor results from MovieRecommendation sample?

### ISSUE THREAD

**Issue by Plasma** [dotnet/machinelearning-samples#788]
Hi,

Thank you for the library and samples. I am wondering why the output of the sample at https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/MatrixFactorization_MovieRecommendation/MovieRecommendation/Program.cs produces poor evaluation results:

```
Root Mean Squared Error : 0.958253197881931
RSquared: 0.454105067953565
```

According to https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/metrics `Root Mean Squared Error (RMs-loss)` should be closer to `0` , and `RSquared` should be closer to `1`.

Are these numbers still "good" for this recommendation engine? What would "bad" numbers look like?

Thanks

**Comment by luisquintanilla** [comment]
Hi @Plasma 

Thank you for your feedback. The main purpose of these samples is to illustrate how to achieve the tasks as opposed to provide an "optimal" model. Although ideally, we'd like to provide the best model as well. The guidance on the metrics is accurate and that's what you should strive for. One of the main contributors to model performance is the data. In this case, it may be an issue with the dataset. We'll try to find a dataset that produces better results.
