### ISSUE TITLE
Yolo3 - how to transform images coming into the model ?

### ISSUE THREAD

**Issue by LordTrololo** [dotnet/machinelearning-samples#808]
Hi,
so I used the [following tutorial](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx#create-a-parser-to-post-process-model-outputs) but instead of the yolo2 I used my own (pretrained) Yolo3 Onnx model. Application is image object detection.

Now my model is different in one aspect:
- The images my model uses need to be floats. With an OpenCV Mat this would look like this:
```
mat.ConvertTo(mat, DepthType.Cv32F);
mat = mat / 255.0;
```

However I am not sure how to transform these images in the scope of the code/tutorial. I tried something on the lines of doing this :
```
var normalize = mlContext.Transforms.NormalizeBinning(outputColumnName: MyModelSettings.ModelInput, inputColumnName: nameof(ImageNetData.ImagePath), maximumBinCount: 255);
binningNormalizer = normalize.Fit(data);

//then continuing with the stuff from tutorial
var pipeline = mlContext.Transforms.LoadImages(outputColumnName: MyModelSettings.ModelInput, imageFolder: imagesFolder, inputColumnName: nameof(ImageNetData.ImagePath))
                .Append(mlContext.Transforms.ResizeImages(outputColumnName: MyModelSettings.ModelInput, imageWidth: ImageNetSettings.imageWidth, imageHeight: ImageNetSettings.imageHeight, inputColumnName: MyModelSettings.ModelInput))
... 
```
But I cannot get it to work. This is relatively trivial when one can grasp the mat/array etc. but I do not know where to "grasp" with ML.

Did someone else had similar problem and if so how did you solve it?

**Comment by luisquintanilla** [comment]
Hi @LordTrololo ,

You can take a look at this code sample that has some sort of normalization / transforms on images. 
Custom Transform
https://github.com/dotnet/machinelearning-samples/blob/8697bec3e9c78beb2c3c4d3f915551c85bcdcb39/samples/modelbuilder/ImageClassification_Azure_LandUse/LandUseML.Model/NormalizeMapping.cs#L11

NormalizeMapping Custom Transform used in Pipeline
https://github.com/dotnet/machinelearning-samples/blob/master/samples/modelbuilder/ImageClassification_Azure_LandUse/LandUseML.ConsoleApp/ModelBuilder.cs#L45

**Comment by DeveloperNo579212** [comment]
I did try to use this NormalizeMapping Custom Transform to my pipeline using onnx file as input,
but fail in prediction as I get only one classification regardsless of the class of the input image.
I had same problem but succeded in the normalization I left out in the python implementation,
target2 = (target2.astype(np.float32) / 127.0) - 1.  If I do the same normalization here I get same
failure as without a normalization in use in python.
