### ISSUE TITLE
Regression with image

### ISSUE THREAD

**Issue by Neoplayer** [dotnet/machinelearning-samples#812]
How to concatenate image with some Single values? I was trying to convert image to `ExtractPixels` and `LoadRawImageBytes` but I can't find any way to concatenate this with single values.

**Comment by luisquintanilla** [comment]
Hi @Neoplayer 

By concatenate, I assume you mean in addition to the feature vector containing your image pixel information you want to add other columns to your feature vector. In that case, you can use the `Concatenate` transform to create a single vector with all your data.

https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/train-machine-learning-model-ml-net#working-with-expected-column-types
