### ISSUE TITLE
compilation error: Cannot convert type 'Microsoft.ML.ITransformer' to 'Microsoft.ML.Data.TransformerChain

### ISSUE THREAD

**Issue by webtrainingroom** [dotnet/machinelearning-samples#817]
Hello !
i am getting compilation error at following code, would you please check ?

sing (var stream = new FileStream(CSV_TestData, FileMode.Open, FileAccess.Read, FileShare.Read))
            {
                **trainedModel = mlContext.Model.Load(stream, out var modelInputSchema);**
            }

I am getting following error : 
Error CS0266	Cannot implicitly convert type 'Microsoft.ML.ITransformer' to 'Microsoft.ML.Data.TransformerChain<Microsoft.ML.Data.RegressionPredictionTransformer<Microsoft.ML.Trainers.LinearRegressionModelParameters>>'. An explicit conversion exists (are you missing a cast?)

Look at:
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/Regression_TaxiFarePrediction

**Comment by antoniovs1029** [comment]
Hi, @webtrainingroom .

I will later try to build this  sample to see if I get the same compilation error. But just by looking into the code right now, it looks to me that you shouldn't be getting that compilation error.

Are you running the sample as it is found [here](https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction/TaxiFarePredictionConsoleApp/Program.cs)? or have you modified it before trying to build it?

If you have modified the sample before building, then simply changing this line should fix the problem:
```C#
trainedModel = (mlContext.Model.Load(stream, out var modelInputSchema)) as TransformerChain<RegressionPredictionTransformer<LinearRegressionModelParameters>> ;
```

**Comment by webtrainingroom** [comment]
Hello @antoniovs1029 ,

I am trying to run the sample as explained [here](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/Regression_TaxiFarePrediction).

After altering the above line as you suggested, the code producing following error.
![image](https://user-images.githubusercontent.com/37655243/81923944-0a942680-95fc-11ea-991a-eadb1807ff76.png)

I am also attaching the test and train data files here, in case you want to know!  
[taxi-fare-train1.xlsx](https://github.com/dotnet/machinelearning-samples/files/4627680/taxi-fare-train1.xlsx)
[taxi-fare-test1.xlsx](https://github.com/dotnet/machinelearning-samples/files/4627681/taxi-fare-test1.xlsx)
