### ISSUE TITLE
Model with custom layers

### ISSUE THREAD

**Issue by SirMrDexter** [dotnet/machinelearning-samples#826]
I am trying to write the digit recognizer solution here with ML.Net.
https://www.kaggle.com/yassineghouzam/introduction-to-cnn-keras-0-997-top-6#3.-CNN

So far I haven't found a way to create a CNN model in there. All documentation and samples are based on loading a pretrained model. Is it possible with ML.Net to do something like in that link. If so, can you point me to some docs/samples for it.

**Comment by Lynx1820** [comment]
Hi @SirMrDexter, 

Checkout [#5208](https://github.com/dotnet/machinelearning/issues/5208)
