### ISSUE TITLE
LSTM Data Input

### ISSUE THREAD

**Issue by ladodc** [dotnet/machinelearning-samples#828]
Hi, I have made and trained LSTM model with tf.keras, saved it in ONNX format. Later on I want to load and predict the data with ML.NET. But I do not know how to prepare data in 3D format (samples, time_steps, features) as LSTM expected. Does anybody know how to solve this problem? 
`
IDataView dataView = mlContext.Data.LoadFromEnumerable<InputData>(data)
`
How to define InputData in the right form for LSTM model.

**Comment by antoniovs1029** [comment]
This is a duplicate of : https://github.com/dotnet/machinelearning/issues/5273

We'll continue the discussion there.
