### ISSUE TITLE
F# samples need to be migrated to the new "Dynamic API available since v0.6"

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning-samples#83]
All the F# samples in this repo are still using the deprecated LearningPipeline API and need to be migrated to the new "Dynamic API", like we're doing with the C# samples.

Contributions from the community will be very much welcomed! 👍

**Comment by mariuszwojcik** [comment]
I plan to work on porting **BinaryClassification_CreditCardFraudDetection** for F#.

**Comment by kunjee17** [comment]
@mariuszwojcik if that is ok with you I ll take regression taxi fare, regression bike sharing and Deep Learning Image Classification (this one is new I ll port from C#) .

**Comment by kunjee17** [comment]
@mariuszwojcik I guess there is a language constraint to implement things in C# way. I did file a issue to in F# language repo. Hopefully things will be solved. Linking it [here](https://github.com/fsharp/fslang-suggestions/issues/162) for reference.

cc/ @CESARDELATORRE @dsyme

**Comment by kunjee17** [comment]
@mariuszwojcik you can start working if you have solved the issue. And I'll pull it from there. I haven't changed much other that few c# bits I forgot to change. I'll continue from that. Thanks

**Comment by kunjee17** [comment]
@mariuszwojcik I guess you solved it. Thanks man. I am on holidays for Diwali. I ll start working again from next week. So, let me know whatever is pending so will start from there.

**Comment by mariuszwojcik** [comment]
@kunjee17 Happy Diwali !!! Have a great holidays. Will keep you posted with my progress.

**Comment by CESARDELATORRE** [comment]
@mariuszwojcik - Closing this issue as the migration of the F# samples is work in progress thanks to you guys! 👍

**Comment by dsyme** [comment]
@CESARDELATORRE How far through the migration work are we, do we have a tracking issue for what remains to be done?  I know I promised to help and I've noticed work progressing, just wanted to know what's left to do, thanks
