### ISSUE TITLE
Fit Method, The asynchronous operation has not completed.

### ISSUE THREAD

**Issue by Aleksey1555** [dotnet/machinelearning-samples#833]
Hello.
Please Help!
I try to compile the code from example
[this link](https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Training/ImageClassification.Train/Program.cs)

I run it, but on this line:
```
// 3. Load Images with in-memory type within the IDataView and Transform Labels to Keys (Categorical)
  IDataView shuffledFullImagesDataset = mlContext.Transforms.Conversion.
           MapValueToKey(outputColumnName: "LabelAsKey", inputColumnName: "Label", keyOrdinality: KeyOrdinality.ByValue)
          .Append(mlContext.Transforms.LoadRawImageBytes(outputColumnName: "Image",
                  imageFolder: fullImagesetFolderPath,
                  inputColumnName: "ImagePath"))
           .Fit(shuffledFullImageFilePathsDataset)
           .Transform(shuffledFullImageFilePathsDataset);
```

i get error: **System.InvalidOperationException: 'The asynchronous operation has not completed.'**
Please Help!

**Comment by XamlBrewer** [comment]
Hi,
after upgrading the NuGet package from v1.5.0 to v1.5.1, the exact same exception happens also in the taxi fare prediction sample (https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/Regression_TaxiFarePrediction):

var trainedModel = trainingPipeline.Fit(trainingDataView);

**Comment by Aleksey1555** [comment]
Thanks, work now!
