### ISSUE TITLE
PNG image doesn't look well in high contrast mode

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/machinelearning-samples#836]
The png images in the README doesn't appear well in high contrast mode.

_Originally posted by @Youssef1313 in https://github.com/dotnet/machinelearning-samples/pull/835#issuecomment-666333139_

**Comment by Youssef1313** [comment]
There is a parallel image in docs that was fixed in https://github.com/dotnet/docs/pull/16215.
The fix here will be just the same for that image.

**Comment by luisquintanilla** [comment]
Hi @Youssef1313 

Thanks for this tip. If anyone from the community would be willing to help out with this, it'd be greatly appreciated.

**Comment by tomaszcekalo** [comment]
Hello. I like ML.NET and I'm looking for a first issue to contribute to. 
About those images, which ones need reworking? Is it purple on white larger images? Or black app type symbols with transparent background?

![image](https://user-images.githubusercontent.com/5594285/119227683-6ea2d200-bb0f-11eb-9aeb-34296c757ea2.png)

**Comment by Youssef1313** [comment]
@tomaszcekalo Thanks for attempting to jump into this issue. The image is:

https://github.com/dotnet/machinelearning-samples/blob/main/samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/docs/images/sdnet2018decksamples.png

The issue basically is there is a black text in a transparent background. When the actual background is black, the text becomes unreadable.

If you're going to convert it to jpg, don't forget to update the link for the image in this readme:

https://github.com/dotnet/machinelearning-samples/blob/ba98d520e67a2840a3c50410885a24f361632567/samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/README.md

**Comment by Youssef1313** [comment]
@tomaszcekalo It might be easiest to just take the image from https://github.com/dotnet/docs/pull/16215.
