### ISSUE TITLE
Object detection  Sample 

### ISSUE THREAD

**Issue by mas1515** [dotnet/machinelearning-samples#844]
hello 
how train custom object detector 
with ml.net ????

is it possible make ocr with ml.net ???

**Comment by luisquintanilla** [comment]
Hi @mas1515 ,

There is no sample at the moment in this repo, but you can use ML.NET Model Builder to train a custom object detection model. 

https://marketplace.visualstudio.com/items?itemName=MLNET.07

In the meantime, you can check out this blog post for a general sense of how to use that scenario.

https://www.arafattehsin.com/beyond-sentiment-analysis-object-detection-with-ml-net/
