### ISSUE TITLE
More features in DeepLearning_ImageClassification_Training

### ISSUE THREAD

**Issue by tolokonnikov** [dotnet/machinelearning-samples#845]
Hi!
How can i add more features to pipline for DeepLearning_ImageClassification_Training example or different image recognition example? Can i add more vectors with image, for example color feature or size feature? Not Label.
Thanks!

**Comment by DevLob-zz** [comment]
if u can share ur approach if u solved ur issue would be grateful

**Comment by tolokonnikov** [comment]
I did not solve my issue but decided will search different path

**Comment by DevLob-zz** [comment]
> I did not solve my issue but decided will search different path

Good luck my friend
