### ISSUE TITLE
[OnnxObjectDetection] System.AccessViolationException: 'Attempted to read or write protected memory. in SetupMlNetModel

### ISSUE THREAD

**Issue by sanme98** [dotnet/machinelearning-samples#920]
Either I tried to run the web or app version, i also have this error. The code just fresh cloned from the git repository without any changes. I'm using VS 2019 Version 16.10.3 with preview feature _Enable ML.NET Model Builder_ turned on. Windows version is Win10 20H2 64bit. CPU AMD Ryzen 5 4000 Series.

System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

Code: (OnnxModelConfigurator.cs(25)
```
var pipeline = mlContext.Transforms.ResizeImages(resizing: ImageResizingEstimator.ResizingKind.Fill, outputColumnName: onnxModel.ModelInput, imageWidth: ImageSettings.imageWidth, imageHeight: ImageSettings.imageHeight, inputColumnName: nameof(ImageInputData.Image))
                            .Append(mlContext.Transforms.ExtractPixels(outputColumnName: onnxModel.ModelInput))
                            .Append(mlContext.Transforms.ApplyOnnxModel(modelFile: onnxModel.ModelPath, outputColumnName: onnxModel.ModelOutput, inputColumnName: onnxModel.ModelInput));
```

![image](https://user-images.githubusercontent.com/5364763/129117844-02eeda9f-7c6d-40d1-a635-a09fb527dd17.png)

**Comment by sanme98** [comment]
I found the root cause, the OnnxRuntime was set to version 1.4.1, it should update to latest version (1.8.1). Once updated and recompile, both web & app are running fine.

@luisquintanilla Please help to update the sample code?

![image](https://user-images.githubusercontent.com/5364763/129134688-c5acf4c9-427c-4893-a1cb-3d356bc10e92.png)

**Comment by jrsilva24** [comment]
This worked for me as well
