### ISSUE TITLE
PLplot not working in TaxiFarePrediction

### ISSUE THREAD

**Issue by AliYildizoz909** [dotnet/machinelearning-samples#931]
Hi, I downloaded the **TaxiFarePrediction** project as it is. When I run it I get the following exception.

```
System.TypeInitializationException: 'The type initializer for 'PLplot.Native' threw an exception.'
```
![image](https://user-images.githubusercontent.com/40477291/140016351-72242a8d-9e2b-4e58-b2c5-f0115460bf3d.png)

**Comment by AliYildizoz909** [comment]
I solved the problem by installing .net core 2.2 from [here](https://dotnet.microsoft.com/en-us/download/dotnet/2.2).

**Comment by chancezheng** [comment]
https://github.com/surban/PLplotNet/issues/2, skip to the end
